liferay/liferay-npm-tools

packages/liferay-npm-scripts/src/config/liferay-npm-scripts-build-deps-clay.json, packages/liferay-npm-scripts/src/config/liferay-npm-scripts-build-deps-liferay.json, packages/liferay-npm-scripts/src/config/liferay-npm-scripts-build-deps-metal.json, packages/liferay-npm-scripts/src/utils/deep-merge.js, packages/liferay-npm-scripts/src/utils/get-merged-config.js
Hey @bryceosterhaus, this just adds a manual list of dependencies known to Portal as a first step. Could you review and merge together with https://github.com/bryceosterhaus/liferay-npm-tools/pull/10 and release a new version?
=> Fixes #6 - Uses deepmerge.all to merge more than one object

CONTRIBUTING.md
Closes: https://github.com/liferay/liferay-npm-tools/issues/48
=> feat: add CONTRIBUTING.md (#48)

packages/liferay-npm-scripts/README.md
Based on the comments in #65, it wasn't necessarily obvious [what the "theme" task was for](https://github.com/liferay/liferay-npm-tools/pull/65#issuecomment-480158819). So I looked at the README and saw that the other tasks are documented and this one probably should be too.
Related: https://github.com/liferay/liferay-npm-tools/issues/64
=> doc: explain "theme", "theme build" in scripts README (#64)

.travis.yml, package.json
Closes: https://github.com/liferay/liferay-npm-tools/issues/69
=> feat: set up Travis (#69)

packages/liferay-npm-scripts/src/index.js, packages/liferay-npm-scripts/src/scripts/build.js, packages/liferay-npm-scripts/src/scripts/eject.js, packages/liferay-npm-scripts/src/scripts/test.js, packages/liferay-npm-scripts/src/scripts/theme.js, packages/liferay-npm-scripts/src/utils/babel.js, packages/liferay-npm-scripts/src/utils/get-merged-config.js, packages/liferay-npm-scripts/src/utils/soy.js, packages/liferay-npm-scripts/src/utils/spawnSync.js
Just some things to clean-up before I roll in support for invoking webpack via liferay-npm-scripts. No behavior changes expected, although our test suite basically covers nothing, so can't be 100% sure until I try it all in portal.
=> Apply minor clean-up

packages/liferay-npm-scripts/src/config/eslint.config.js
Doesn't cover everything, but hits the most pervasively used cases.
=> feat(scripts): add some globals to the default list

package.json, packages/liferay-npm-scripts/package.json, yarn.lock
In order to get this fix that is required by liferay-portal:
https://github.com/liferay/eslint-config-liferay/pull/48
=> chore(scripts): update eslint-config-liferay dep to v4.1.1

.travis.yml, .travis/before_install.sh, .travis/install.sh, .travis/script.sh, package.json, packages/liferay-npm-scripts/src/scripts/theme.js, packages/liferay-npm-scripts/test/scripts/theme.js, packages/liferay-npm-scripts/test/utils/expandGlobs.js, packages/liferay-npm-scripts/test/utils/spawnSync.js
Not sure whether this will work, although support apparently includes a Bash environment, so there is a chance:
https://blog.travis-ci.com/2018-10-11-windows-early-release
The idea is to catch in CI the kind of issues that are fixed here:
https://github.com/liferay/liferay-npm-tools/pull/150
=> feat: run CI on Windows

packages/liferay-npm-bundler-preset-liferay-dev/package.json, yarn.lock
Duplication in the yarn.lock will be resolved when I update liferay-npm-scripts too.
=> chore: update liferay-npm-bundler-preset-liferay-dev dependencies

packages/liferay-npm-scripts/src/format/index.js
Now that https://github.com/liferay/liferay-npm-tools/pull/247 has been merged, let's use `getPaths()` here to remove some repetition.
=> refactor: use getPaths() to eliminate repetition

packages/liferay-npm-scripts/src/config/babel.json
=> fix(scripts): disables useStrict in commonjs transform by default

package.json, packages/liferay-npm-scripts/package.json, yarn.lock
Release notes:
https://github.com/liferay/eslint-config-liferay/releases/tag/v12.0.0
Of particular interest:
- feat!: add no-duplicate-class-names, sort-class-names, trim-class-names rules
- fix(sort-imports): make sure "metal" sorts before "metal-dom"
- feat!: add no-restricted-globals rule
=> feat(scripts)!: update eslint-config-liferay to v12.0.0

packages/liferay-jest-junit-reporter/test/index.js, packages/liferay-npm-scripts/test/scripts/format.js, packages/liferay-npm-scripts/test/scripts/theme.js, packages/liferay-npm-scripts/test/scripts/webpack.js, packages/liferay-npm-scripts/test/utils/spawnMultiple.js
This is a follow-up to this comment:
https://github.com/liferay/liferay-npm-tools/pull/293/files#r335972590
=> refactor: simplify mock setup

packages/liferay-npm-scripts/src/jsp/README.md, packages/liferay-npm-scripts/src/jsp/formatJSP.js, packages/liferay-npm-scripts/src/jsp/lintJSP.js, packages/liferay-npm-scripts/src/jsp/processJSP.js, packages/liferay-npm-scripts/src/scripts/lint.js, packages/liferay-npm-scripts/test/jsp/formatJSP.js, packages/liferay-npm-scripts/test/jsp/lintJSP.js, packages/liferay-npm-scripts/test/scripts/lint.js
~Still a WIP. I spent a few hours a day fighting with ESLint's APIs before finally concluding that I just had to roll a bunch of stuff on my own. I have only tested it lightly, which is why that last commit is a WIP. I'll clean this up and test this further tomorrow.~
Closes: https://github.com/liferay/liferay-npm-tools/issues/309
=> feat: lint JS inside JSP files

.eslintrc.js, packages/liferay-js-insights/index.js, packages/liferay-npm-scripts/bin/liferay-npm-scripts.js, packages/liferay-npm-scripts/package.json, packages/liferay-npm-scripts/src/config/eslint.config.js, packages/liferay-npm-scripts/src/config/stylelint.json, packages/liferay-npm-scripts/src/index.js, packages/liferay-npm-scripts/src/jsp/Lexer.js, packages/liferay-npm-scripts/src/jsp/isJSP.js, packages/liferay-npm-scripts/src/jsp/lintJSP.js, packages/liferay-npm-scripts/src/scripts/check.js, packages/liferay-npm-scripts/src/scripts/check/preflight.js, packages/liferay-npm-scripts/src/scripts/fix.js, packages/liferay-npm-scripts/src/scripts/lint.js, packages/liferay-npm-scripts/src/scripts/lint/stylelint/isSCSS.js, packages/liferay-npm-scripts/src/scripts/lint/stylelint/lintSCSS.js, packages/liferay-npm-scripts/src/scripts/lint/stylelint/plugins/no-block-comments.js, packages/liferay-npm-scripts/src/utils/SignalHandler.js, packages/liferay-npm-scripts/src/utils/getMergedConfig.js, packages/liferay-npm-scripts/src/utils/hasExtension.js, packages/liferay-npm-scripts/src/utils/spawnMultiple.js, packages/liferay-npm-scripts/test/index.js, packages/liferay-npm-scripts/test/scripts/lint.js, packages/liferay-npm-scripts/test/scripts/lint/stylelint/plugins/no-block-comments.js, packages/liferay-npm-scripts/test/utils/spawnMultiple.js, yarn.lock
~Marking this as a draft until our rule list is defined.~
---
Currently doing nothing because we don't have a set of rules defined yet, but you can see a couple of sample rules commented out that I used for testing.
As noted in previous commits, the API is, unfortunately, async only, which means we need to change a bunch of other places to make them async-capable.
Some other limitations are noted inline, the most obvious of which is that stylelint has an autofix functionality that is very loudly labeled as "experimental":
> Note: It's an experimental feature. It currently does not respect special comments for disabling stylelint within sources (e. g. `/* stylelint-disable */`). Autofixing will be applied regardless of these comments.
>
> If you're using both these special comments and …
=> feat(scripts): add stylelint

package.json, packages/liferay-changelog-generator/src/index.js, packages/liferay-npm-scripts/package.json, packages/liferay-npm-scripts/src/jsp/Lexer.js, packages/liferay-npm-scripts/src/jsp/dedent.js, packages/liferay-npm-scripts/src/jsp/lex.js, packages/liferay-npm-scripts/src/scripts/theme.js, packages/liferay-npm-scripts/src/utils/deepMerge.js, packages/liferay-npm-scripts/src/utils/getRegExpForGlob.js, packages/liferay-npm-scripts/src/utils/permute.js, packages/liferay-npm-scripts/test/utils/getRegExpForGlob.js, yarn.lock
Changes: https://github.com/liferay/eslint-config-liferay/releases/tag/v19.0.0
=> chore(scripts)!: update to eslint-config-liferay v19.0.0

package.json, packages/liferay-npm-scripts/package.json, yarn.lock
To get this bugfix:
https://github.com/liferay/eslint-config-liferay/pull/146
=> chore(scripts): bump eslint-config-liferay to v19.0.1

packages/liferay-npm-scripts/README.md, packages/liferay-npm-scripts/contrib/prettier/prettier.js
And pick a less-ridiculous name for the (unused) debug channel.
=> docs(scripts): improve wrapper documentation

packages/liferay-changelog-generator/README.md
Closes: https://github.com/liferay/liferay-npm-tools/issues/403
=> docs(changelog): add FAQ section to changelog generator README

packages/liferay-npm-scripts/src/config/eslint.config.js
Seeing as Iván ran into this in [the pull](https://github.com/andresfulla/liferay-portal/pull/221) that he is currently preparing testing out the new bundler.
Related: https://github.com/liferay/liferay-npm-tools/issues/402
=> feat(scripts): recognize liferay-npm-bundler.config.js

packages/liferay-js-publish/src/index.js
See first commit for a full description of what this PR does.
=> feat: add support for prerealease versions

packages/liferay-js-publish/src/index.js
=> fix: change contains() to includes()

packages/liferay-npm-scripts/src/presets/standard/dependencies/liferay.js, packages/liferay-npm-scripts/src/scripts/storybook.js, packages/liferay-npm-scripts/src/storybook/frontend-js-react-web.mock.js, packages/liferay-npm-scripts/src/storybook/webpack.config.js
This will help address the 'module not found' error occurring when running Storybook for one of the features in Search Infra. Thanks!
@thektan
=> feat: add 'frontend-js-react-web' mock js to Storybook config files

packages/liferay-npm-scripts/src/utils/filterChangedFiles.js, packages/liferay-npm-scripts/src/utils/run.js, packages/liferay-npm-scripts/test/utils/filterChangedFiles.js, packages/liferay-npm-scripts/test/utils/run.js
Rebase of https://github.com/liferay/liferay-npm-tools/pull/436 with a commit-revert pair written out of the history.
=> feat(scripts): don't filter files when liferay-npm-scripts updates

packages/liferay-npm-scripts/package.json
Release notes:
https://github.com/liferay/liferay-npm-tools/releases/tag/liferay-npm-bundler-preset-liferay-dev%2Fv4.3.1
=> chore(scripts): update liferay-npm-bundler-preset-liferay-dev to v4.3.1

packages/liferay-npm-bundler-preset-liferay-dev/config.json
[This was released two weeks ago](https://www.npmjs.com/package/@clayui/layout) and we're ready to start using it in liferay-portal:
=> chore(preset): add @clayui/layout package to preset

packages/liferay-npm-scripts/package.json
In order to get: https://github.com/liferay/liferay-npm-tools/pull/459
[v4.4.0 Release notes](https://github.com/liferay/liferay-npm-tools/releases/tag/liferay-npm-bundler-preset-liferay-dev%2Fv4.4.0)
=> chore(scripts): update preset dependency to v4.4.0

packages/liferay-npm-scripts/package.json
In order to get: https://github.com/liferay/liferay-npm-tools/pull/462
[Release notes](https://github.com/liferay/liferay-npm-tools/releases/tag/liferay-npm-bundler-preset-liferay-dev%2Fv4.5.0).
=> chore(scripts): update preset dependency to v4.5.0

packages/liferay-npm-scripts/package.json
Release notes:
https://github.com/liferay/liferay-npm-tools/releases/tag/liferay-npm-bundler-preset-liferay-dev%2Fv4.6.0
Motivation: principally to get:
https://github.com/liferay/liferay-js-toolkit/pull/632
=> chore(scripts): update liferay-npm-bundler-preset-liferay-dev to v4.6.0
