liferay/liferay-npm-tools

- packages/liferay-npm-scripts/src/config/jest.json
With the move to Yarn workspaces in the portal, this configuration was causing all tests that use liferay-npm-scripts to run their tests to fail, because the reporter module is now hoisted up to the top of the workspace.
It is defined as a dependency of the liferay-npm-scripts, so we can count on it being installed, and just reference it by its name; the node module resolution algorithm will find it.
Associated LPS: https://issues.liferay.com/browse/LPS-92609
> Don't use relative path for jest testResultsProcessor

- packages/liferay-npm-scripts/src/utils/get-merged-config.js
Noticed while preparing #37 that if I made a local override in my "package.json" it had no effect. That's because liferay-npm-scripts is taking whatever user settings are provided (either in "package.json" or in a "jest.config.js" file) and then overwriting them with the top-level defaults defined in its own "config/jest.json" file.
This seems to be the wrong behavior for defaults, which should only take effect in the absence of a more explicit setting.
Before merging this, we should check the portal repo to make sure we're not relying on the old behavior anywhere; at the very least we can clean out some settings from the repo that can't possibly be having any effect.
> Change merge order so that local overrides have precedence

- packages/liferay-npm-scripts/src/scripts/eject.js
"eject" explodes as follows:
```
? Are you sure you want to eject? This action is permanent. Yes
(node:95558) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'soy' of undefined
at generateBuildScript (/Users/greghurrell/code/liferay-npm-tools/packages/liferay-npm-scripts/example/eject/before/node_modules/liferay-npm-scripts/src/scripts/eject.js:35:13)
at module.exports (/Users/greghurrell/code/liferay-npm-tools/packages/liferay-npm-scripts/example/eject/before/node_modules/liferay-npm-scripts/src/scripts/eject.js:95:10)
at inquirer.prompt.then (/Users/greghurrell/code/liferay-npm-tools/packages/liferay-npm-scripts/example/eject/before/node_modules/liferay-npm-scripts/src/index.js:47:33)
at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:95558) …
```
> fix: broken "eject" in liferay-npm-scripts (#44)

- packages/liferay-npm-bundler-preset-liferay-dev/package.json
- yarn.lock
Ideally this would have been done in #43 as part of the solution to #42, but I didn't realize we needed to update these packages as well.
You know the change is good when it only leads to red lines in the lockfile diff.
> chore: Update dependencies on liferay-npm-build-tools packages (#42)

- copyright.js
- package.json
- packages/liferay-jest-junit-reporter/__tests__/index.js
- packages/liferay-jest-junit-reporter/index.js
- packages/liferay-npm-scripts/bin/liferay-npm-scripts.js
- packages/liferay-npm-scripts/src/index.js
- packages/liferay-npm-scripts/src/scripts/babel.js
- packages/liferay-npm-scripts/src/scripts/build.js
- packages/liferay-npm-scripts/src/scripts/eject.js
- packages/liferay-npm-scripts/src/scripts/format.js
- packages/liferay-npm-scripts/src/scripts/lint.js
- packages/liferay-npm-scripts/src/scripts/soy.js
- packages/liferay-npm-scripts/src/scripts/test.js
- packages/liferay-npm-scripts/src/utils/deep-merge.js
- packages/liferay-npm-scripts/src/utils/generate-soy-dependencies.js
- packages/liferay-npm-scripts/src/utils/get-merged-config.js
- packages/liferay-npm-scripts/src/utils/get-user-config.js
- packages/liferay-npm-scripts/src/utils/move-to-temp.js
- packages/liferay-npm-scripts/src/utils/spawnSync.js
Adds these scripts to package.json, in addition to "format" and "format:check" which we already had:
- "lint": reports lints but doesn't fix them.
- "lint:fix": reports lints and fixes autofixable lints.
An earlier version of this commit in the PR had a "fix" script that was equivalent to "format" followed by "lint:fix" but we're temporarily backing that out until we come up with a better name.
Test plan: Run all the new scripts; see "format" fix formatting issues in one file, and "lint" report these issues which I then fixed:
packages/liferay-npm-scripts/src/index.js
61:4  error  Unexpected console statement  no-console
packages/liferay-npm-scripts/src/scripts/eject.js
36:33  error  Unnecessary escape character: \"  no-useless-escape
38:5   error  Unnecessary escape character: \" …
> chore: separate formatting and linting scripts

- packages/liferay-npm-scripts/__tests__/utils/spawnSync.js
- packages/liferay-npm-scripts/package.json
- packages/liferay-npm-scripts/src/scripts/test.js
- packages/liferay-npm-scripts/src/utils/spawnSync.js
Test plan: `yarn test` in "liferay-npm-scripts". By way of an integration test, also do this (which will error out due to a config clash):
```
../../node_modules/.bin/liferay-npm-scripts test
● Validation Error:
Configuration options testMatch and testRegex cannot be used together.
Configuration Documentation:
https://jestjs.io/docs/configuration.html
/Users/greghurrell/code/liferay-npm-tools/packages/liferay-npm-scripts/src/utils/spawnSync.js:36
throw new Error(
^
Error: Command jest --config /Users/greghurrell/code/liferay-npm-tools/packages/liferay-npm-scripts/TEMP_jest.config.json exited with code 1
zsh: exit 1     ../../node_modules/.bin/liferay-npm-scripts test
```
Closes: https://github.com/liferay/liferay-npm-tools/issues/38
> fix: don't silently swallow failures in spawnSync (#38)

- packages/liferay-npm-scripts/src/config/jest.json
Before this commit, when you ran `yarn test` in a directory like "modules/apps/layout/layout-content-page-editor-web", you'd see:
jest-haste-map: Haste module naming collision: layout-content-page-editor-web
The following files share their name; please adjust your hasteImpl:
* <rootDir>/package.json
* <rootDir>/build/unzipped-jar/package.json
Test plan: Apply this change in the modules/node_modules copy of liferay-npm-scripts and run `yarn test` in the directory mentioned above. See the tests pass and no warnings from jest-haste-map any more.
Closes: https://github.com/liferay/liferay-npm-tools/issues/53
> fix: jest-haste-map warnings about module naming collisions (#53)

- packages/liferay-npm-scripts/src/utils/spawnSync.js
In liferay-portal on Windows, but apparently only on some Windows machines, we have this mysterious error during builds:
[exec] > Task :apps:frontend-taglib:frontend-taglib-clay:npmRunBuild
[exec] Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".
In short, `spawnSync` is trying to set the `PATH` to ensure that we use its local Babel 7, but that doesn't seem to be working, at least on the version of Windows that I tested, and the versions used by the people who have reported build difficulties over the last few days. Stack trace shows the top-level Babel v6 binary being used instead. So when liferay-npm-scripts writes out its `.babelrc` file, it references `@babel/preset-env`, which is a version 7 package, and everything blows up.
The fix is to grab the local executable, if …
> fix: improve executable selection on Windows (#62)

- packages/liferay-npm-scripts/__fixtures__/scripts/theme/modules/apps/frontend-theme-fjord/frontend-theme-fjord/.gitignore
- packages/liferay-npm-scripts/__fixtures__/scripts/theme/modules/apps/frontend-theme/frontend-theme-classic/.gitignore
- packages/liferay-npm-scripts/__fixtures__/scripts/theme/not/the/apps/you/are/looking/for/.gitignore
- packages/liferay-npm-scripts/__tests__/scripts/theme.js
- packages/liferay-npm-scripts/src/index.js
- packages/liferay-npm-scripts/src/scripts/theme.js
With this, we can replace scripts like theses ones in liferay-portal:
"build": "gulp build --css-common-path ./build_gradle/frontend-css-common --styled-path ../../frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled --unstyled-path ../../frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled"
with:
"build": "liferay-npm-scripts theme build"
I added a bunch of tests because this involves traversing the filesystem and I didn't want to screw it up. Using runtime traversal rather than hardcoding relative paths in order to make us _somewhat_ resilient to possible future changes in the structure of the filesystem layout. As it is right now, we have two variants in liferay-portal, which I have reflected in the structure of the …
> feat: add "theme" subcommand (#64)

- CONTRIBUTING.md
- package.json
- packages/liferay-npm-bundler-preset-liferay-dev/package.json
This it the simplest thing I could think of to get tests running from the top-level. Ideally though, we could just run jest once at the top. That would be pretty easy to set-up, but would require a bit of extra work to make it happen while still preserving the ability to run the tests at the level of the individual packages, so I am keeping it simple for now.
Test plan: `yarn test` at top level and see all run. Then `yarn test` at individual package level to prove that that still works too.
Closes: https://github.com/liferay/liferay-npm-tools/issues/67
> feat: add top-level shortcut to run all tests (#67)

- CONTRIBUTING.md
- packages/liferay-jest-junit-reporter/.yarnrc
- packages/liferay-jest-junit-reporter/package.json
- packages/liferay-npm-bundler-preset-liferay-dev/.yarnrc
- packages/liferay-npm-bundler-preset-liferay-dev/package.json
- packages/liferay-npm-scripts/.yarnrc
- packages/liferay-npm-scripts/package.json
As you can see in the changes to CONTRIBUTING.md, the release process can be made simpler by doing two things:
- Adding `.yarnrc` config files that set up the templates for the correct tag and release commit message formats.
- Using `"preversion"` scripts to automatically run the CI checks (formatting, linting, and testing) before cutting a release.
Note that we run the checks for *all* packages in the repo, which is overkill, but it is the simplest thing to do. If a problem in package A ever blocks you from publishing package B you can pass `--ignore-scripts`, but you should probably just fix package A because we want the CI to be green on every commit anyway. As a follow-up, we should make it possible to run the tests independently within a given repo.
There are still further steps we …
> feat: simplify release process (#50)

- packages/liferay-npm-scripts/__fixtures__/scripts/webpack/sample/webpack.config.dev.js
- packages/liferay-npm-scripts/__tests__/scripts/webpack.js
- packages/liferay-npm-scripts/package.json
- packages/liferay-npm-scripts/src/index.js
- packages/liferay-npm-scripts/src/scripts/build.js
- packages/liferay-npm-scripts/src/scripts/webpack.js
- yarn.lock
At the moment all this does is run "webpack", which will use the default "webpack.config.js" found in the current directory.
I have a liferay-portal PR under development which does some shuffling around of files in that repo in order to make this possible:
https://github.com/wincent/liferay-portal/pull/8
Next steps will include getting a usable "watch" command in place, and exploring whether we can offer a meaningful default config here. We'll also have the option of integrating the webpack build into the standard "liferay-npm-scripts build" command: the idea there will could be to run the webpack step if a config file is present; in order to make that happen though, will need to make some further changes to the upstream projects (for example, segments/segments-web is already using a …
> feat: add "wepback" subcommand to liferay-npm-scripts

- packages/liferay-npm-scripts/package.json
- packages/liferay-npm-scripts/src/config/babel.json
- yarn.lock
We are already using these in a number of places in the liferay-portal repo, and they are almost certain to be enshrined as-is in a future version of the standard:
- rest-spread is at stage 4: https://github.com/tc39/proposal-object-rest-spread
- class-properties are at stage 3 and implemented in Babel, Node, Chrome etc: https://github.com/tc39/proposal-class-fields
>  feat: add class-properties and object-rest-spread support

- packages/liferay-npm-scripts/package.json
- yarn.lock
So that modules in the liferay-portal repo can rely on it being present rather than pulling it in independently. I think liferay-npm-scripts is the right place for it because all webpack usage in the liferay-portal is happening via this package anyway.
> feat: provide standard version of babel-loader

- packages/liferay-npm-scripts/__tests__/utils/deep-merge.js
- packages/liferay-npm-scripts/src/config/babel.json
- packages/liferay-npm-scripts/src/utils/deep-merge.js
- packages/liferay-npm-scripts/src/utils/get-merged-config.js
As described in the related issue, our merge implementation is using the pre-2.0 version of the array merge algorithm in the "deepmerge" package. They removed it because it was a "complicated thing".
In the case of merging Babel configs it verily breaks them, because you can specify plugins and presets as either `'name'` or `['name', options]`. Here's a reduced example of some surprising behavior:
- merging `['a', 'b', ['c']]`
- into `['d', 'e']`
- yields: `['d', 'e', ['c'], 'b']`
ie. `'a'` disappears into the void.
See the test cases included in this commit for a real-life example taken from segments-web. The old algorithm would cause the `@babel/plugin-proposal-class-properties` plugin to vanish.
The implementation here doesn't intend to handle all possible edge cases (for example, it …
> feat: add Babel merge strategy to get-merged-config.js

- packages/liferay-npm-scripts/src/scripts/build.js
Unlike what I did with Babel in #82, just add a `try`/`finally` wrapper. I wanted something more generic and reusable for Babel because we use it in 3 places, but we only use liferay-npm-bundler in one place, so something simpler and more direct is called for.
Test plan: install in liferay-portal, add a `throw` after bundling, and run the `yarn build` in a module with an .npmbundlerrc file (eg. frontend-js-web). See the original config file is restored despite the error.
Closes: https://github.com/liferay/liferay-npm-tools/issues/71
> fix: recover original .npmbundlerrc after failures (#71)

- packages/liferay-npm-scripts/src/scripts/build.js
We noticed that in the frontend-js-web build, the bundle wasn't being properly transpiled for IE.
This change makes sure that the babel config is respected.
Internal ticket: https://issues.liferay.com/browse/LPS-95870
> fix: run weback during builds using shared utility

- packages/liferay-npm-scripts/__tests__/utils/deep-merge.js
- packages/liferay-npm-scripts/src/utils/deep-merge.js
As described in the related issue, Babel has various optional shorthand conventions for identifying plugins and presets, which means that it is possible to refer to the same module under different names. Babel will then complain about duplicates with an error message which isn't very helpful:
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.
plugins: [
['some-plugin', {}],
['some-plugin', {}, 'some unique name'],
]
It doesn't mention the actual names that are duplicated, or even if it's a preset or a plugin that it's complaining about. This, combined with the fact that we dynamically generate a ".babelrc" at runtime, means that this is very confusing for people not familiar with the tooling; they may look at …
> feat: enforce canonical preset and plugin names (#89)

- packages/liferay-npm-scripts/src/index.js
- packages/liferay-npm-scripts/src/scripts/build.js
- packages/liferay-npm-scripts/src/scripts/test.js
- packages/liferay-npm-scripts/src/utils/set-env.js
This will allow Jest, for example, to use its normal default ("test").
Test plan: Use `yarn add -W path/to/liferay-npm-scripts` to install this version in the liferay-portal repo's "modules/" workspace root. Then change to a module that uses "liferay-npm-scripts" (eg. "segments/segments-web") and run `yarn build`; see:
```
$ liferay-npm-scripts build
Using NODE_ENV: production
Successfully compiled 39 files with Babel.
...
```
Then run `env NODE_ENV=development yarn build` and see:
```
$ liferay-npm-scripts build
Using pre-existing NODE_ENV: development
Successfully compiled 39 files with Babel.
...
```
Closes: https://github.com/liferay/liferay-npm-tools/issues/88
> feat: set NODE_ENV only for builds (#88)

- packages/liferay-npm-scripts/__tests__/index.js
- packages/liferay-npm-scripts/__tests__/utils/get-merged-config.js
- packages/liferay-npm-scripts/src/index.js
- packages/liferay-npm-scripts/src/utils/get-merged-config.js
Based on discussion about use of `console.log` in:
https://github.com/liferay/liferay-npm-tools/pull/91
I did a quick audit and found that there are only two other places in this package where we use `console.log` and both should probably throw errors instead of just logging a message and proceeding.
For example, current behavior:
$ liferay-npm-scripts formatz
'formatz' is not a valid command for liferay-npm-scripts.
$ liferay-npm-scripts
'undefined' is not a valid command for liferay-npm-scripts.
(Both exit with status code 0.)
Behavior after this commit:
$ liferay-npm-scripts formatz
/path/to/index.js:46
throw new Error(
^
Error: liferay-npm-scripts requires a valid command (build, format, lint, test, theme, webpack)
$ liferay-npm-scripts
/path/to/index.js:46
throw new Error(
^
Error: …
> refactor: teach getMergedConfig() and index to reject invalid types

- README.md
Because we don't use Babel to make these packages and they get run in the context of liferay-portal without transpilation, we should advise people to use a recent version so as not to choke on the various "modern JS" features that we use pretty freely in this codebase.
> doc: recommend using a recent version of NodeJS

- packages/liferay-npm-scripts/README.md
- packages/liferay-npm-scripts/__tests__/scripts/lint.js
- packages/liferay-npm-scripts/src/scripts/lint.js
In integrating `prettier` with liferay-portal I have found modules that have "checkFormat" scripts defined even though they don't have any source code (for example, wrapper modules like frontend-js-metal-web, which is basically just declares dependencies but doesn't contain any committed code of its own under "src/"):
"scripts": {
"build": "liferay-npm-scripts build",
"checkFormat": "liferay-npm-scripts lint",
"format": "liferay-npm-scripts format"
},
For these, `prettier` will complain about not finding any files that match the default globs. You would think that you could define an `npmscripts.config.js` file, then, that removes the globs, but that won't work either (because `prettier` will complain that you didn't pass any globs).
I am going to explore if there is any downside to …
> feat: provide a way to skip linting/formatting entirely

- packages/liferay-npm-scripts/src/presets/standard/index.js
As described in the related issue, we determined that:
- We want test code in liferay-portal to reside in a top-level "test" directory inside each module.
- Currently there are only two modules which don't follow that pattern:
- One is dead code which I am proposing to remove here: https://github.com/brunobasto/liferay-portal/pull/1036
- The other can be moved; currently testing a PR that does that here: https://github.com/wincent/liferay-portal/pull/28
Closes: https://github.com/liferay/liferay-npm-tools/issues/95
> feat: expand lint/format globs to cover "test" (#95)

- packages/liferay-npm-scripts/README.md
- packages/liferay-npm-scripts/__tests__/scripts/check.js
- packages/liferay-npm-scripts/src/index.js
- packages/liferay-npm-scripts/src/presets/standard/index.js
- packages/liferay-npm-scripts/src/scripts/check.js
- packages/liferay-npm-scripts/src/scripts/fix.js
BREAKING CHANGE: For consistency, "liferay-npm-scripts lint" and "liferay-npm-scripts format" are now "liferay-npm-scripts check" and "liferay-npm-scripts fix", respectively. The corresponding glob properties in "npmscripts.config.js" have also been renamed from "lint" to "check", and from "format" to "fix".
See the related issue for a lengthy explanation.
Related: https://github.com/liferay/liferay-npm-tools/issues/110
> refactor(scripts)!: rename "lint"/"format" to "check"/"fix" (#110)

- packages/liferay-npm-scripts/package.json
- packages/liferay-npm-scripts/src/utils/getMergedConfig.js
- yarn.lock
Just to reduce our dependency footprint a little and remove some "clutter" from the source. We added this in 08fa78d03ebd197 but as far as I can tell there is no need for the keys to be sorted (the merged configs are never committed to the repo or inspected by a human, and we don't do anything order-sensitive with them either).
Note that we still have another copy of sort-keys in the yarn.lock, but that one is a transitive dependency so I'm going to ignore it for now.
> chore: remove sort-keys dependency

- packages/liferay-npm-scripts/package.json
- packages/liferay-npm-scripts/src/config/eslint.config.js
- yarn.lock
- Switching the parser to babel-eslint equips us to handle static class properties.
- Setting `{env: {es6: true}}` makes sure that globals defined by ES6 are registered.
- Setting `{parserOptions: {ecmaFeatures: {jsx: true}}}` let's us parse JSX without choking.
- Setting `{parserOptions: {ecmaFeatures: {ecmaVersion: 2018}}}` let's us parse object rest spread.
In other words, these changes allow us to avoid errors like this (caused by object rest spread):
error  Parsing error: Unexpected token ..
or (caused by JSX):
error  Parsing error: Unexpected token <
or (caused by static class properties):
error  Parsing error: Unexpected token =
With this, we can run ESLint on all of liferay-portal without seeing any "Parsing error" in the output: …
> feat(scripts): equip ESLint to handle new ES features + JSX (#118)

- packages/liferay-npm-scripts/__fixtures__/scripts/lint/modules/.eslintignore
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/modules/apps/frontend-js/frontend-js-aui-web/.eslintignore
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/modules/apps/frontend-js/frontend-js-web/.gitignore
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/modules/apps/rogue/project/yarn.lock
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/modules/apps/segments/segments-web/.eslintignore
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/modules/yarn.lock
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/somewhere/subtree/with/a/lock/file/.gitignore
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/somewhere/subtree/yarn.lock
- packages/liferay-npm-scripts/src/presets/standard/index.js
- packages/liferay-npm-scripts/src/scripts/lint.js
- packages/liferay-npm-scripts/test/scripts/lint.js
Two things here:
Firstly, we need a hack in order to be able to target just "*.es.js" files with ESLint without torpedoing the use of Prettier on all files.
Secondly, by design, apparently, ESLint won't let you have more than one .eslintignore file. It will only look in the current directory, unless you pass an explicit `--ignore-path` option. If you do that, or it finds an .eslintignore in the current directory, it will skip over any local "eslintIgnore" property that might exist in the package.json too.
However, we kind of need this ability because we run `liferay-npm-scripts lint` in two modes:
1. From the "modules/" root, where we lint everything in the repo.
2. From individual subproject directories, like "modules/apps/segments/segments-web".
In both cases, we want to provide some …
> feat(scripts): make it possible to target "*.es.js" alone

- packages/liferay-npm-scripts/src/config/eslint.config.js
Normally "root: true" is handy way to prevent unexpected surprises from happening (due to random stuff like having an unrelated ESLint config file in your home directory, and having that conflict with project-local settings).
In our case, however, we don't want to create a "root: true" config in the current directory, but rather in the liferay-portal top-level "modules/" root. That way, we can run `liferay-npm-scripts lint` from the top level and have it well controlled, and we can also run it from a project sub-directory and have it benefit from the configuration cascade (for example all the way up to, but not past, the "modules/" root).
So, this commit removes "root: true" from here, and I'll make the corresponding inverse change in liferay-portal by adding a "root: true" config to the …
> feat: drop "root: true" from eslint config

- packages/liferay-npm-scripts/src/scripts/lint.js
Our original intent here was to apply the same linting config everywhere, and force it to be that way via `--no-eslintrc`.
Given our change of plans (in which we're rolling out the linting gradually and with exceptions) we'll very much need to have the ability to apply per-directory overrides. So we have to remove the switch.
> feat(scripts)!: drop `--no-eslintrc` from invocation

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
This brings us the "liferay/react" variant, which we'll be needing in select places within liferay-portal (and ultimately, not-so-select places, once we roll out react more broadly).
> chore: update eslint-config-liferay to v4.0.0

- packages/liferay-npm-scripts/src/config/eslint.config.js
This stops ESLint from complaining about `require` and `module.exports` and such in these files.
> feat(scripts): teach "lint" to use "node" env for config files

- packages/liferay-npm-scripts/src/config/eslint.config.js
At the moment, liferay-portal has an `.eslintrc.js` in the top-level `modules/` folder that only contains a `root: true` property and nothing else.
When `liferay-npm-scripts` runs, it will look for a "local" user config and merge it with the one that we provide, writing the result to a temporary file that gets passed to ESLint via the `--config` option.
So, one of three things happens:
1. You run it from `modules/`, and you get a config file that contains the base plus `root: true`.
2. You run it from `modules/apps/*/*`, and you get a config file that contains the base plus your local config; because ESLint will walk up the tree looking for parent configs, it will eventually stop when it sees `root: true` in the `modules/` directory.
3. Your editor runs it for you. Depending on where you …
> feat(scripts): tweak lint config for use in IDEs

- package.json
- packages/liferay-jest-junit-reporter/test/__snapshots__/index.js.snap
- packages/liferay-jest-junit-reporter/test/index.js
- packages/liferay-npm-scripts/package.json
- packages/liferay-npm-scripts/src/config/eslint.config.js
- yarn.lock
Additionally, use the new "liferay/portal" preset instead of the base "liferay" one for our linting.
This will make two new rules apply in liferay-portal:
- liferay/no-it-should
- liferay-portal/no-side-navigation
For more details, see the "Custom rules" section at the bottom of the README:
https://github.com/liferay/eslint-config-liferay/tree/70c26d756cc6#custom-rules
> chore(scripts): update eslint-config-liferay dep to v4.1.0

- packages/liferay-npm-scripts/src/config/babel.json
I created a `babel.test.json` to separate the babel configurations between the test and build scripts. I didn't use the [`const isTest = api.env('test');` in `babel.config.js` example from the jest docs](https://jestjs.io/docs/en/getting-started#using-babel) so we could continue to use the `babelMerge` function in `deepMerge.js` as is.
But I'm also not sure what the implications would be if we only applied the following to the current `babel.json` instead of creating a separate `babel.test.json`.
```
{
"presets": [
[
"@babel/preset-env",
{
"targets": {
"node": "current"
}
}
]
],
...
```
*Also as an additional note, currently the only place that will have async/await in tests is still in a dev branch yet to be merged in master. https://github.com/thektan/liferay-portal/blob/LPS-96356-fix-fr …
> feat: support async/await in jest tests (#105)

- packages/liferay-npm-scripts/src/scripts/format.js
- packages/liferay-npm-scripts/src/scripts/lint.js
- packages/liferay-npm-scripts/src/utils/expandGlobs.js
- packages/liferay-npm-scripts/src/utils/findRoot.js
- packages/liferay-npm-scripts/src/utils/getRegExpForGlob.js
- packages/liferay-npm-scripts/src/utils/preprocessGlob.js
- packages/liferay-npm-scripts/src/utils/readIgnoreFile.js
- packages/liferay-npm-scripts/test/scripts/format.js
- packages/liferay-npm-scripts/test/utils/expandGlobs.js
- packages/liferay-npm-scripts/test/utils/getRegExpForGlob.js
- packages/liferay-npm-scripts/test/utils/preprocessGlob.js
In this commit we handle globbing internally for Prettier (future commit will do the same for ESLint, but I want to make things at least somewhat readable by splitting this up), which means that we can switch from spawning the `prettier` executable to calling its API directly internally.
Motivation:
- Frontend checks got turned off in CI because they were global.
- We need to be able to target a subset of files in CI.
- That is difficult because we are relying on how two different tools (ESLint and Prettier) deal with two kinds of globs each ("include" globs passed on the command line and "exclude" globs passed in via .eslintirgnore/.prettierignore files).
- ESLint is using one glob engine and supporting utilities (minimatch, is-glob, and glob-parent), and these in turn depend on …
> feat: handling globbing internally for Prettier

- packages/liferay-npm-scripts/__fixtures__/scripts/lint/modules/apps/frontend-js/frontend-js-aui-web/.eslintignore
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/modules/apps/frontend-js/frontend-js-web/.gitignore
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/modules/apps/rogue/project/yarn.lock
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/modules/apps/segments/segments-web/src/index.es.js
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/somewhere/subtree/with/a/lock/file/.gitignore
- packages/liferay-npm-scripts/__fixtures__/scripts/lint/somewhere/subtree/yarn.lock
- packages/liferay-npm-scripts/src/scripts/lint.js
- packages/liferay-npm-scripts/test/scripts/lint.js
Analog to what we did with Prettier in:
https://github.com/liferay/liferay-npm-tools/pull/141
I removed all the `findProjectIgnoreFiles()` stuff because we never ended up actually using it in liferay-portal, so it is unneeded complexity. (In the end we went with inline suppressions and created tickets to get rid of those.)
As before, tested in liferay-portal with a diff like this:
https://gist.github.com/wincent/dd173f939ba5b1c3b5906bffc4ba99a5
(see that one includes some formatting changes caused by our increased Prettier coverage).
> feat: handling globbing internally for ESLint

- packages/liferay-npm-scripts/src/config/eslint.config.js
As discussed [here](https://github.com/wincent/liferay-portal/pull/13/commits/2f86ef7c28554f0924be470d93068766bba1715a#r300623290).
In liferay-portal, we basically run all our Jest scripts in NodeJS.
There are exactly two usages of Karma that in theory could end up running anywhere:
- modules/apps/analytics/analytics-client-js
- modules/apps/portal-search/portal-search-web
In practice, it looks like they'll run in ChromeHeadless for analytics-client-js, and Firefox for portal-search-web, via:
https://github.com/kenjiheigel/liferay-karma-config
As those are minority usages, and we want all tests to run via `liferay-npm-scripts` moving forward, I think this change is acceptably imprecise, and will allow us to get rid of some lint suppressions.
> feat(scripts): configure ESLint to treat jest like node

- packages/liferay-npm-scripts/src/scripts/lint.js
We explicitly manage the list of paths that we want to lint and pass that to ESLint's programmatic interface, but it still complains about files like ".eslintrc.js" because it is ignored by default (along with other dot files, apparently: see https://github.com/eslint/eslint/issues/6645).
The warnings look like this:
0:0 warning File ignored by default. Use a negated ignore pattern
(like "--ignore-pattern '!<relative/path/to/filename>'") to override
By passing in a negated "ignorePattern" configuration of "!*" we can avoid those warnings. This will fix about 8 spurious warnings in a run across all of liferay-portal.
Related: https://issues.liferay.com/browse/LPS-97876
> fix(scripts): stop ESLint's spurious "ignored by default" warnings

- packages/liferay-npm-scripts/src/scripts/lint.js
Just noticed that if we have one autofixable issue we'll print a message like:
ESLint checked 526 files, found 1 error, found 215 warnings, 1 issue
are potentially fixable with lint:fix
ie. ("1 issue are").
We do correctly pluralize however:
ESLint checked 526 files, found 1 error, found 215 warnings, 2
issues are potentially fixable with lint:fix
Rather than complicating the pluralization code, just drop the "are"; the message still reads coherently, and arguably it's better in the more concise format anyway:
ESLint checked 526 files, found 1 error, found 215 warnings, 1 issue
potentially fixable with lint:fix
> fix(scripts): remove sometimes ungrammatical wording

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
This means that copyright headers will be checked/fixed in liferay-portal even when running `yarn checkFormat`/`yarn format` from inside a project subdirectory (ie. "modules/apps/foo/bar"), which is something that product team developers are going to reasonably expect to work.
https://github.com/liferay/eslint-config-liferay/releases/tag/v4.2.0
> chore: update eslint-config-liferay to v4.2.0

- packages/liferay-npm-scripts/package.json
- yarn.lock
Locking to version 7.0.0, which is the latest release and the one that segments/segments-web and app-builder/app-builder-web are effectively using in liferay-portal right now.
Closes: https://github.com/liferay/liferay-npm-tools/issues/139
> feat: bundle babel/preset-react with liferay-npm-scripts (#139)

- packages/liferay-npm-scripts/src/utils/expandGlobs.js
`path.join()` on Windows will produce paths of the form "a\\b\\c" instead of "a/b/c", causing the regular expressions produced by `getRegExpForGlobs()` to not match.
@kresimir-coko verified that the fix in this PR is working for him on Windows.
In a separate PR I'm going to see whether we can reliably run the Travis CI tests on Windows to catch this kind of problem in the future.
> fix(scripts): make file glob expansion work on Windows

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
Of principal interest to us here is the new "liferay/metal" preset that we'll be able to use in liferay-portal to eliminate a fair number of lint suppressions:
https://github.com/liferay/eslint-config-liferay/releases/tag/v4.3.0
> chore: update to eslint-config-liferay v4.3.0

- packages/liferay-npm-scripts/src/utils/findRoot.js
On "master" our root is "modules".
On "master-private" it is "modules/private".
> feat: teach findRoot() to work in master-private branch

- packages/liferay-npm-scripts/src/scripts/test.js
Reading the `jest --help` output just now I see this:
```
--config, -c     The path to a jest config file specifying how to
find and execute tests. If no rootDir is set in
the config, the directory containing the config
file is assumed to be the rootDir for the
project.This can also be a JSON encoded value
which Jest will use as configuration.   [string]
```
This means that we can simplify our config management by just passing it in as string. No need to mess with temporary files on the filesystem.
> refactor(scripts): simplify Jest config set-up

- packages/liferay-npm-scripts/__fixtures__/utils/findRoot/modules/private/yarn.lock
- packages/liferay-npm-scripts/__fixtures__/utils/findRoot/modules/yarn.lock
- packages/liferay-npm-scripts/src/utils/findRoot.js
- packages/liferay-npm-scripts/test/utils/findRoot.js
This is the "Plan B" related to this comment:
https://github.com/brianchandotcom/liferay-portal-ee/pull/25312#issuecomment-509784609
As I explained there, our approach was to treat the two directories that contain "yarn.lock" files as separate little worlds (which, from Yarn's point of view, they are).
However, there is more than one way to skin a cat, and we can slightly tweak our definition of what "root" means for the purposes of linting and formatting (which are the only tasks where we are currently using `findRoot()`).
This commit makes the top (public) "modules" be considered the root and that's where we look up our ignore files. The files that I had added in that PR above are basically subsets of what is in the top-level files, simply because there is less stuff in "master-private" …
> chore(scripts): tweak "master-private" concept of "root"

- .eslintrc.json
We can drop all this because we already get equivalent (and standardized!) config from eslint-config-liferay.
> refactor: remove unnecessary ESLint config

- packages/liferay-npm-scripts/src/presets/standard/index.js
Because we do our own globbing and make explicit calls to the ESLint API, we no longer need this workaround.
Tested in liferay-portal:
Before:
Prettier checked 1450 files, found 1 file with problems
ESLint checked 551 files, found 0 errors, found 4 warnings
After:
Prettier checked 1450 files, found 1 file with problems
ESLint checked 551 files, found 0 errors, found 4 warnings
Also note that I tested in a module that has 0 ".es.js" files, and saw that ESLint didn't complain:
eg. in modules/apps/analytics/analytics-client-js
Prettier checked 30 files, found 0 files with problems
ESLint checked 0 files, found 0 errors, found 0 warnings
> refactor(scripts): remove now-unnecessary ESLint workaround

- packages/liferay-npm-scripts/package.json
- yarn.lock
As a starting point, add `@testing-libary/react` and `@testing-library/jest-dom`, which are the two we'd discussed previously here:
https://github.com/liferay/liferay-npm-tools/issues/108
Test plan:
`yarn add -W --dev ~code/liferay-npm-tools/packages/liferay-npm-scripts` in liferay-portal checkoud, remove old deps (jest-dom and react-testing-library) from "modules/apps/segments/segments-web", update imports to use new libary names, run `yarn test`.
> feat(scripts): add @testing-library dependencies

- packages/liferay-npm-scripts/src/jest/transformBabel.js
Fixes the problem where any use of `async` in tests would lead to:
ReferenceError: regeneratorRuntime is not defined
Thanks to `@babel/preset-env` and our use of a recent "targets" configuration for test files, we should be able to use `async` without any transforms (our version of Node, v10.15.1, supports `async` directly), but I believe I broke that in 3c5a9c5c217e167394d1771136d8.
That commit had the effect of partially (but not totally) neutralizing our Babel config because our overrides (which explicitly set the target to `"node": "10.15"`) were getting blowing away by the transform which just uses vanilla `@babel/preset-env` without options.
This change here makes sure that we always pass the merged user config directly to Jest's `createTransformer()` call. It's also possible that …
> fix(scripts): make async work in tests again

- packages/liferay-npm-scripts/src/config/prettier.json
Due to request here:
https://github.com/brianchandotcom/liferay-portal/pull/75741#issuecomment-511581392
Related internal ticket:
https://issues.liferay.com/browse/LPS-98277
> style: use double quotes for JSX attributes

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
Of principal interest to us because it will allow us to sort JSX properties in liferay-portal.
Release notes:
https://github.com/liferay/eslint-config-liferay/releases/tag/v4.4.0
> chore(scripts): update to eslint-config-liferay v4.4.0

- packages/liferay-npm-scripts/package.json
- yarn.lock
This should probably have been included in the initial PR that bundled our test dependencies (#164). This one was requested [here](https://github.com/liferay/liferay-frontend-guidelines/issues/49#issuecomment-510459340) and it seems like a worthy candidate for inclusion for a few reasons:
- It is an official package in the `@testing-library` organization, so we can expect a comparable level of support to that which the other `@testing-library` packages receive, and we've already opted to depend on (ie. trust) those.
- The package is a (literally) [very thin wrapper](https://github.com/testing-library/user-event/blob/251f287995c8a71/src/index.js) around the `fireEvent()` API, easily audited.
- The library encourages us to test what really matters (product behavior, often initiated by user …
> feat(scripts): add @testing-library/user-event

- packages/liferay-npm-bundler-preset-liferay-dev/config.json
To make it easier to backport liferay-npm-scripts to v7.1.x of liferay-portal, make the version requirements specified in the bundler preset super loose: all that we really care about is that "some version of frontend-js-web and frontend-taglib" are available, it doesn't matter which.
Test plan: `yarn add` my local changes in liferay-portal and deploy "fragment-web". See it still work in "master".
> chore(preset): use loose version requirements to facilitate backporting

- CONTRIBUTING.md
- packages/liferay-jest-junit-reporter/package.json
- packages/liferay-npm-bundler-preset-liferay-dev/package.json
- packages/liferay-npm-scripts/package.json
- packages/liferay-npm-scripts/src/utils/git.js
- packages/liferay-npm-scripts/src/utils/run.js
- publish.js
I have been doing a lot of [releases](https://github.com/liferay/liferay-npm-tools/releases) of late — about 20 in the last month — so I wanted to finally go ahead and add some more automation here which should make the release process both quicker and less error-prone.
This implements the last of the ideas in #50. (Previously we implemented a "preversion" script and ".yarnrc" files to create the appropriate release commits and tags.)
We add a "postversion" script that basically does this:
git rev-parse --abbrev-ref HEAD
git diff --quite
git push upstream master
git checkout stable
git merge --ff-only master
git push upstream stable --follow-tags
git checkout master
yarn publish
Obviously with abundant checks and guards and prompts along the way.
Test plan: I've sort-of-kind-of tested …
> feat: add "postversion" scripts to automate publishing

- packages/liferay-npm-scripts/src/scripts/test.js
Reported here:
https://github.com/liferay/liferay-npm-tools/issues/176
On Windows, test runs fail:
$ yarn test
yarn run v1.15.2
$ liferay-npm-scripts test
The system cannot find the file specified.
Command L:\repo\master-portal-dev\modules\node_modules\liferay-npm-scripts\node_modules\.bin\jest --config {...} exited with code 1
error Command failed with exit code 1.
(Edited for brevity: the config elided with "..." is about 2k characters long.)
Seems that we are running into the limit described here:
https://devblogs.microsoft.com/oldnewthing/?p=41553
> If you are using the ShellExecute/Ex function, then you become subject
> to the INTERNET_MAX_URL_LENGTH (around 2048) command line length limit
> imposed by the ShellExecute/Ex functions.
So, let's just revert the commit and go back to how …
> fix: Revert "refactor(scripts): simplify Jest config set-up" (#176)

- packages/liferay-npm-scripts/test/scripts/format.js
Before:
PASS  packages/liferay-npm-scripts/test/scripts/format.js
● Console
console.log packages/liferay-npm-scripts/src/utils/log.js:9
Prettier checked 1 file, found 0 files with problems, fixed 1 file
After:
PASS  packages/liferay-npm-scripts/test/scripts/format.js
To avoid possible confusion during version tagging, as described here:
https://github.com/liferay/liferay-npm-tools/pull/175#issuecomment-513147027
- Run `yarn version`.
- "preversion" script runs, including tests, console output is visible.
- "postversion" script runs, which publishes package.
- Developer wonders why we're publishing even though we supposedly had to fix (and should therefore commit) a misformatted file.
> test(scripts): suppress log output in formatting tests

- packages/liferay-npm-scripts/src/scripts/format.js
As explained [here](https://github.com/liferay/liferay-npm-tools/pull/175#issuecomment-513144786), the summary output can be a bit confusing because it was made to be consistent with ESLint (which can report confusing things like "found 0 issues, fixed 10 issues" -- this makes it sound like it fixed issues that it didn't find). We can't easily change the ESLint summary because it is baked into the reporter, but we can change the Prettier one.
With this small tweak we now have these kinds of output that are hopefully totally clear:
- When checking (or fixing) and there are no problems:
Prettier checked 1461 files
- When checking and 1 or 2 files have formatting problems or syntax errors:
Prettier checked 1461 files, 1 file has problems
Prettier checked 1461 files, 2 files have problems
- …
> feat(scripts): improve Prettier summary output

- packages/liferay-npm-scripts/package.json
- yarn.lock
With the update to storybook, our dependencies changed in the yarn.lock file. When the new version was deployed to liferay-portal [here](https://github.com/brianchandotcom/liferay-portal/pull/76714) something changed in the resolution that meant that babel-jest got installed inside node_modules/jest-config/node_modules instead of being hoisted to the top level.
I ran the tests locally and they worked only because of a rogue copy of babel-jest that I had in liferay-portal/../node_modules(!!) because I must have accidentally run a `yarn` command there at some point in ancient history.
Test plan: `yarn add` this to liferay-portal; confirm that `babel-jest` is again in the top-level.
> fix: make babel-jest dependency explicit

- packages/liferay-npm-bundler-preset-liferay-dev/config.json
We currently have some missing configuration imports in our `preset-dev`. This causes some unnecessary modules to be processed.
Based on a quick estimate, it adds around 8s per module, so fixing this would provide a significant speed boost to build time.
**Test Plan:**
- Build a module in portal using `liferay-npm-scripts` that depends on `frontend-js-web`
- Assert that the resulting `classes/node_modules` does not contain the `frontend-js-web` dependencies (`liferay-amd-loader`, `svg4everybody`...)
> fix: adds missing clay and frontend-js-web dependencies configuration

- packages/liferay-npm-scripts/src/utils/generateSoyDependencies.js
If you had a single dependency like "metal-slider" then we were making a glob like `{path/to/directory/metal-slider}/src/**/*.soy`, which was failing to match anything at all.
For a "{a,b,c}"-style glob to work, it has to have at least two comma-separated items in it. "{a}" will not match "a".
So, in the case that the dependencies list only contains one item, use the item as-is; otherwise, wrap in "{"/"}" and join with commas.
> fix: make generateSoyDependencies() work with lone dependencies

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
Breaking because eslint-config-liferay v5 itself has a breaking change (will produce new errors due to additional rule).
> chore!: update eslint-config-liferay to v5.0.0

- packages/liferay-npm-scripts/src/scripts/test.js
- packages/liferay-npm-scripts/src/utils/log.js
- packages/liferay-npm-scripts/src/utils/setEnv.js
Due to recent changes in liferay-portal, we started setting an explicit NODE_ENV of "production" by default, which meant that Jest's usual behavior of assuming "test" no longer worked, and tests broke.
We resolved that in https://github.com/liferay/liferay-portal/commit/0741aabb5d201578a0 but in this commit we want to make ourselves 100% resilient to any future changes in the way `liferay-npm-scripts test` is invoked by always setting a NODE_ENV of "test", no matter what.
Here's what you see with no NODE_ENV:
$ yarn test
$ liferay-npm-scripts test
Using NODE_ENV: "test"
And if NODE_ENV is "test":
$ env NODE_ENV=test yarn test
$ liferay-npm-scripts test
Using NODE_ENV: "test"
And if NODE_ENV is anything else:
$ env NODE_ENV=development yarn test
$ liferay-npm-scripts test
Overriding …
> feat: force the use of a "test" NODE_ENV when running jest

- packages/liferay-jest-junit-reporter/package.json
- packages/liferay-npm-bundler-preset-liferay-dev/package.json
- packages/liferay-npm-scripts/package.json
fix: update/remove bad links and add missing links in package.json files
Mostly so that the links back to the repo from the NPM pages will work:
- https://www.npmjs.com/package/liferay-jest-junit-reporter
- https://www.npmjs.com/package/liferay-npm-bundler-preset-liferay-dev
- https://www.npmjs.com/package/liferay-npm-scripts
I don't think anybody is using the `npm bugs` command on these packages, so the "bugs" link is pretty useless. In any case, `npm bugs` is smart enough to tack "/issues" onto the end of the repo URL anyway.
> fix: update/remove bad links and add missing links in package.json files

- packages/liferay-jest-junit-reporter/src/index.js
- packages/liferay-jest-junit-reporter/test/__snapshots__/index.js.snap
- packages/liferay-jest-junit-reporter/test/index.js
Originally sent by @john-co here: https://github.com/wincent/liferay-npm-tools/pull/2
My plan is to cut a tagged preview release which we can try out in liferay-portal, although based on what I see in the Jest tests, I think it's going to work.
> feat(reporter): include module name at end of classname (#136)

- packages/liferay-npm-bundler-preset-liferay-dev/config.json
In service of [LPS-99399](https://issues.liferay.com/browse/LPS-99399) we want to be offer a standard way to mount React apps in liferay-portal which will take care of common needs like:
- Establishing context(s).
- Subscribing to "~destropyPortlet~destroyPortlet" events and automatically calling `unmountComponentAtNode()`.
- etc
The logical place for this will be inside the "frontend-js-react-web" module, so we need configuration to make it easy to `import` from there, which is what this commit adds.
> feat(preset): add "/" import config for frontend-js-react-web

- packages/liferay-npm-scripts/package.json
- yarn.lock
Note the change to the yarn.lock file: this is because we have prepared a beta release of liferay-jest-junit-reporter (1.1.0-beta.1) in a268cb4 but haven't done a non-beta release yet; it's still being tested - see:
https://github.com/liferay/liferay-npm-tools/pull/201
While that's pending, and because liferay-npm-scripts still depends on 1.0.1, v1.0.1 of the package gets added back explicitly to the lockfile.
> chore(scripts): update liferay-npm-bundler-preset-liferay-dev dep

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
Breaking change because we now prohibit the use of `render()` from "react-dom".
> chore!: update to eslint-config-liferay v8.0.0

- publish.js
Yesterday I saw a publish fail with this message:
Failed to automatically publish package due to:
run(): command `yarn publish --non-interactive --otp 501636` exited with status 1
(I think because my OTP token expired by the time the command actually got to talking to the registry servers).
However, the exit status of the process itself it still 0, so it is easy to overlook this message.
If we have an error, let's exit with a status of 1 instead. And also let's include a "cross mark" emoji
Failed to automatically publish package! ❌
run(): command `yarn publish --non-interactive --otp 501636` exited with status 1
to mirror the success output (which uses a check mark):
Done! ✅
You can sanity-check that the package is correctly listed here:
https://www.npmjs.com/package/liferay-npm-scripts
> feat: make failed publishes more obvious

- packages/liferay-npm-scripts/src/utils/getMergedConfig.js
- packages/liferay-npm-scripts/src/utils/getUserConfig.js
We just noticed that when you run the "format" task from a project directory, it doesn't consult the ".prettierrc.js" at the top level.
This is because we tell cosmiconfig not to walk up above the current directory. It seems reasonable that we should be able to safely walk up as high as the "root" (ie. the directory containing the "yarn.lock" file) though.
> fix: search up as high as liferay-portal "root" for user config

- packages/liferay-npm-scripts/src/scripts/fix.js
Previously we ran Prettier then ESLint in our "fix" script which meant that Prettier might wrap the code in a certain way, only to have ESLint change the AST in a way that meant that Prettier would wrap differently on the next run. We should be able to fix that by inverting the order of the fixes.
Note that because we're using `spawnMultiple` an early failure in ESLint won't stop Prettier from running (errors are accumulated and then reported in aggregate at the end).
> fix: swap order of "fix" script ("format" then "lint:fix")

- packages/liferay-npm-scripts/.prettierrc
The one we have at the top-level should suffice.
> chore: remove redundant .prettierrc

- packages/liferay-changelog-generator/.yarnrc
- packages/liferay-changelog-generator/README.md
- packages/liferay-changelog-generator/bin/liferay-changelog-generator.js
- packages/liferay-changelog-generator/package.json
- packages/liferay-changelog-generator/src/index.js
Basically took the changelog generator that we have been using in a few places (from [here](https://github.com/liferay/liferay-js-themes-toolkit/blob/640ec3bf73cc87a34eea90c4673e1881e3401be8/scripts/changelog.js))  and turned it into an NPM package. It has zero dependencies, and you can easily use it without adding it as a dependency (ie. with `npx liferay-changelog-generator`), so I hope this can make our life better without plunging us any deeper into the "Thousands-Of-Packages-Nightmare" in which we currently languish.
Once this is merged and published I'll remove it from liferay-js-themes-toolkit and update our various "CONTRIBUTING" guides to refer to this instead. There are a couple of known limitations listed in the README that I'd like to address soon too.
> feat: add liferay-changelog-generator

- packages/liferay-npm-scripts/package.json
Everything else in the repo -- the top-level LICENSE.txt, the copyright headers, the other package.json files -- thinks the license is BSD-3-Clause, not MIT.
> chore(scripts): correct license type in liferay-npm-scripts package.json

- packages/liferay-changelog-generator/src/index.js
Accept "-f" as a shorthand for "--force" and "-h" as a shorthand for "--help".
Test plan: Run with `--help`, `-h`, `-f`, and `--force`. Run with `f` and see it correctly report an unrecognized option.
(Just wanting to make some trivial change so that I can test the `publish.js` script with this package.)
> feat(changelog-generator): add short options

- packages/liferay-changelog-generator/src/index.js
See changes made by Prettier to the changelogs in these PRs:
- https://github.com/liferay/liferay-js-themes-toolkit/pull/389/files
- https://github.com/liferay/liferay-js-themes-toolkit/pull/390/files
Specifically: `_` gets escaped, and list items have three trailing spaces instead of one.
Note that this means you can't use "_" to indicate italics in your PR titles ("*" will still work though); I'm not sure that's a very useful thing to do anyway.
Test plan: Regenerate the changelogs in the liferay-js-themes-toolkit repo with these changes and confirm that Prettier agrees with the formatting:
git reset --hard v8.1.1
~/code/liferay-npm-tools/packages/liferay-changelog-generator/bin/liferay-changelog-generator.js --regenerate --version=v8.1.1
git add -u
yarn format
git diff --quiet
git …
> feat: make changelog output identical to Prettier

- packages/liferay-npm-scripts/src/utils/spawnSync.js
Make sure that signals in child process get caught and turned into errors, so that our `finally` blocks will run and perform their necessary cleanup even when the user interrupts a build with Ctrl-C.
Originally sent this as:
https://github.com/liferay/liferay-npm-tools/pull/244
But that had two parts, so I am splitting it into:
https://github.com/liferay/liferay-npm-tools/pull/245
And this one so that we can decide independently whether we want both or just one. This one should clearly go in; the other one may not be needed but might be nice to have "just in case".
Companion to: https://github.com/liferay/liferay-npm-tools/pull/243
> fix: don't let signals leave stale files lying around (#242)

- packages/liferay-npm-scripts/src/utils/deepMerge.js
- packages/liferay-npm-scripts/test/utils/deepMerge.js
As explained in the related issue, we have a few places around where we use `finally` to do cleanup of temporary files we leave on the filesystem.
That deals nicely with errors but if you interrupt a build with Ctrl-C the `finally` block(s) won't run. The stale config files (eg. a merged `.babelrc`) that get left behind can cause the next run to fail with a confusing stack trace, usually deep in the bowels of the `deepMerge()` function along the lines of `target.slice()` is not a function.
We should deal with this in depth:
1. Make `deepMerge()` resilient to being run on a previously merged config.
2. Detect a stale merged config file on disk and report the problem to the user in a way that they can understand the fix.
3. Install a sig handler that does clean-up even when a build is …
> fix: don't choke on stale .babelrc files (#242)

- packages/liferay-npm-scripts/src/scripts/build.js
- packages/liferay-npm-scripts/src/scripts/test.js
- packages/liferay-npm-scripts/src/utils/SignalHandler.js
- packages/liferay-npm-scripts/src/utils/withBabelConfig.js
Add a `SignalHandler` module that sets up signal handlers and provides a mechanism for registering callbacks that should be executed when a signal is received.
Originally sent this as:
https://github.com/liferay/liferay-npm-tools/pull/244
But then I realized it should be split into two bits:
1. This bit, the SignalHandler, may be overkill, and we can decide whether we want the complexity or not.
2. The other bit from #244 was making sure that `spawnSync` turns signals in child processes into errors. That on its own may be enough, and should clearly go in.
Companion to: https://github.com/liferay/liferay-npm-tools/pull/243
> feat: add SignalHandler for managing cleanup

- packages/liferay-npm-scripts/src/scripts/format.js
- packages/liferay-npm-scripts/src/scripts/lint.js
- packages/liferay-npm-scripts/src/utils/getPaths.js
Back in ancient history before we knew that we were going to have to implement our own glob expansion, we made a basic `filterGlobs()` function that would take some globs like:
['**/*.js', '**/*.css', '**/*.foo']
And filter them down to a subset:
['**/*.js', '**/*.css']
To keep things simple, we didn't add support for globs that used compound patterns in their extensions (eg. `'**/*.{js,jsx}'`).
Later on, we were forced to implement our own globbing, and part of that was building a function (`preprocessGlob()`) that could preprocess complex globs (eg. `'{src,test}/**/*.js'`) and transform them into a list of simpler globs (eg. `['src/**/*.js', 'test/**/*.js']`).
Looking at the code now, I see that there's no reason to require globs to have simple extensions any more; we can support …
> feat: allow for compound patterns in extensions in globs

- packages/liferay-npm-scripts/src/format/Lexer.js
- packages/liferay-npm-scripts/src/format/README.md
- packages/liferay-npm-scripts/src/format/ReversibleMap.js
- packages/liferay-npm-scripts/src/format/dedent.js
- packages/liferay-npm-scripts/src/format/formatJSP.js
- packages/liferay-npm-scripts/src/format/index.js
- packages/liferay-npm-scripts/src/format/restoreTags.js
- packages/liferay-npm-scripts/src/format/tagReplacements.js
- packages/liferay-npm-scripts/src/format/trim.js
- packages/liferay-npm-scripts/test/format/ReversibleMap.js
- packages/liferay-npm-scripts/test/format/dedent.js
- packages/liferay-npm-scripts/test/format/formatJSP.js
- packages/liferay-npm-scripts/test/format/stripIndents.js
- packages/liferay-npm-scripts/test/format/trim.js
Going to implement some small improvements based on walking through the JSP-formatting code with @julien. ~I have to go, but will finish this later. Still to do:~
> refactor: implement improvements from JSP formatting review

- packages/liferay-changelog-generator/.yarnrc
- packages/liferay-jest-junit-reporter/.yarnrc
- packages/liferay-npm-bundler-preset-liferay-dev/.yarnrc
- packages/liferay-npm-scripts/.yarnrc
It will complain if there is no "type:" prefix in the release commit message.
Example here:
https://github.com/liferay/liferay-npm-tools/pull/263
> fix: make release commit messages satisfy Semantic Pull Requests bot

- packages/liferay-changelog-generator/package.json
- packages/liferay-jest-junit-reporter/package.json
- packages/liferay-js-publish/.yarnrc
- packages/liferay-js-publish/README.md
- packages/liferay-js-publish/bin/liferay-js-publish.js
- packages/liferay-js-publish/package.json
- packages/liferay-js-publish/src/git.js
- packages/liferay-js-publish/src/index.js
- packages/liferay-js-publish/src/run.js
- packages/liferay-npm-bundler-preset-liferay-dev/package.json
- packages/liferay-npm-scripts/package.json
As explained in the README.md, this is just packaging up the existing publish.js script so that it can be used from other projects.
Its only dependency is "cross-spawn": 7.0.0 is out and would be a safe upgrade for us, but it doesn't offer anything that we need (all it does is drop support for old NodeJS versions), so let's stick with "^6.0.5", which is what we're already using in liferay-npm-scripts, so as to avoid unnecessary duplication.
Speaking of duplication, the other thing you'll note is that I have a copy-paste of "git.js" and "run.js" in here from "liferay-npm-scripts". It is only a few lines of trivial code, and avoiding the dependency here is desirable because keeping dependencies in sync, even our own, is a headache.
> feat: extract liferay-js-publish package

- packages/liferay-js-publish/src/index.js
When testing this with eslint-config-liferay, discovered that we were being juuuuust a little bit too strict in here.
This won't catch repos under the Metal org, but basically everything that we're actively developing is under "liferay/" so this is probably good.
> fix(publish): loosen upstream remote regex

- packages/liferay-npm-bundler-preset-liferay-dev/config.json
- packages/liferay-npm-scripts/src/presets/standard/index.js
As per: https://github.com/liferay/liferay-npm-tools/issues/272
> chore(scripts): send build output to "build" instead of "classes" (#272)

- packages/liferay-jest-junit-reporter/package.json
- packages/liferay-npm-bundler-preset-liferay-dev/package.json
Any time we update the reporter or the preset we have to update the scripts as well, because the latter depends on the first two.
Just insert a little, low-tech reminder to do so.
That wouldn't have stopped me from making the mistake that a just made though: we'll need something more for that:
1. Made changes to preset and scripts.
2. Published scripts v10.0.0.
3. Realized error, published preset v2.0.0.
4. Updated scripts dependency on preset.
5. Published scripts v10.0.1.
We'll need a bit more logic and automation to catch/prevent that kind of mistake.
> feat: add reminder to publish liferay-npm-scripts

- packages/liferay-npm-scripts/package.json
- packages/liferay-npm-scripts/src/scripts/build.js
- packages/liferay-npm-scripts/src/utils/soy.js
Test plan: copied this over to liferay-portal and ran a build in frontend-taglib-clay. Saw this output:
$ liferay-npm-scripts build
Using NODE_ENV: "production"
Compiling soy
Generated src/main/resources/META-INF/resources/management_toolbar/ManagementToolbar.soy.js
Finished compiling soy
Successfully compiled 2 files with Babel.
Bundling took 1s
Updated goog.getMsg() -> Liferay.Language.get() in 34 files
✨  Done in 5.69s.
In the output folder, you can see changes like this:
var MSG_EXTERNAL_2532519427604455359 = Liferay.Language.get('select-items');
going to:
var MSG_EXTERNAL_2532519427604455359 = goog.getMsg('select-items');
That sample from:
frontend-taglib-clay$clay-management-toolbar@2.18.1/src/ClayManagementToolbar.soy.js
Closes: …
> feat(scripts): substitute goog.getMsg() calls in soy files (#277)

- packages/liferay-npm-scripts/src/utils/soy.js
Addresses the failure to translate soy files reported here:
https://github.com/petershin/liferay-portal/pull/724#issuecomment-537253992
> fix(scripts): make soy.js correctly expand globs on Windows

- packages/liferay-npm-scripts/package.json
- packages/liferay-npm-scripts/src/config/babel.json
- yarn.lock
This enables the `@babel/plugin-proposal-export-namespace-from` plugin:
https://babeljs.io/docs/en/next/babel-plugin-proposal-export-namespace-from.html
Which allows Babel to process:
export * as X from './x';
This is proposal is at Stage 4:
https://github.com/tc39/proposal-export-ns-from
and got merged into ECMA-262 already:
https://github.com/tc39/ecma262/pull/1174
Without this, we can write the above example as:
import * as X from './x';
export {X};
which is ok, but obviously not as nice. Example commit where I'm employing exactly that workaround:
https://github.com/wincent/liferay-portal/pull/67/commits/f41f93d433b35e210b64731dd4bc6a21cb195234
> feat(scripts): support "export namespace from" in Babel

- packages/liferay-npm-scripts/src/config/babel.json
Otherwise we'll throw an error (because we added code to require canonically formatted names in order to avoid unintended duplicate plugins when we merge configs).
Error: checkBabelName(): expected
"@babel/proposal-export-namespace-from", got
"@babel/plugin-proposal-export-namespace-from"
> fix(scripts): use canonical plugin name format

- packages/liferay-npm-scripts/src/scripts/build.js
- packages/liferay-npm-scripts/src/utils/soy.js
We can avoid the indirection of spawning a separate process with this small change.
Test plan: `yarn add` this to liferay-portal and do `yarn build` in a module that contains soy (eg. frontend-taglib-clay) and see that soy files are cleaned up from src directory after the build.
Closes: https://github.com/liferay/liferay-npm-tools/issues/284
> refactor(scripts): use rimraf API directly (#284)

- packages/liferay-npm-scripts/package.json
Labeling this as a feature because the new version of the preset makes new Clay modules available.
Note that I'm sending this against "master" but we have to cut a maintenance release that is basically "master" minus the changes to the build output directory (d539eca etc). I'll prepare that after this and will see which way looks less hideous; either some revert commits on master or another branch.
> feat(scripts): update preset to latest (v2.1.0)

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
Based on changelog, don't see any thing that looks breaking for us:
https://github.com/eslint/eslint/blob/master/CHANGELOG.md
> chore: update eslint from 6.1.0 to 6.5.1

- package.json
So that if you accidentally do `yarn version --major` at the top level, we'll fail fast instead of bumping the version number and creating a useless commit and tag.
> feat: prevent accidental use of top-level `yarn version`

- packages/liferay-npm-bundler-preset-liferay-dev/config.json
This is a new module where we will be putting React components that don't belong in Clay itself, but which are used in multiple places throughout liferay-portal.
We not putting them in frontend-js-web to avoid bloat there, nor in frontend-js-react-web because that's just plumbing for using React in liferay-portal. You could think of these as being analogous or related to the Clay "Satellites" defined in Lexicon.
> feat(preset): add frontend-js-components-web to the preset

- packages/liferay-npm-scripts/src/config/jest.config.js
- packages/liferay-npm-scripts/src/jest/transformSass.js
- packages/liferay-npm-scripts/src/jest/transformStyles.js
As explained in the inline comments, these transforms allow Jest to work with components that contain SCSS and CSS imports:
import './MyComponents.scss';
Given such an import Jest will otherwise try to read the file and treat it as JS, which obviously won't work. We use the transform here to turn such "modules" into harmless no-ops.
> feat(scripts): teach Jest to deal with new liferay-npm-bundler loaders

- packages/liferay-npm-scripts/README.md
Stale because we aren't using the `check-source-formatting` package
anymore.
> docs(scripts): remove stale link from README

- packages/liferay-npm-scripts/src/scripts/lint.js
- packages/liferay-npm-scripts/test/scripts/lint.js
Only report if there are errors or warnings, and do so in red for errors and yellow if there are only warnings. This matches the ESLint behavior.
Closes: https://github.com/liferay/liferay-npm-tools/issues/317
> fix(scripts): don't use color or report results if successful (#317)

- packages/liferay-npm-scripts/src/config/babel.json
- packages/liferay-npm-scripts/src/utils/getMergedConfig.js
- packages/liferay-npm-scripts/src/utils/runBabel.js
- packages/liferay-npm-scripts/test/utils/getMergedConfig.js
Note that this will require some corresponding changes in liferay-portal, namely, there are two projects which use the incremental-dom plugin:
- https://github.com/liferay/liferay-portal/blob/1f84f9713487704f173e6777781a20d7c38477f6/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-builder/.babelrc
- https://github.com/liferay/liferay-portal/blob/1f84f9713487704f173e6777781a20d7c38477f6/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/.babelrc
I don't think we can turn off the preset for those, but we can disable the individual plugins that the preset activates.
I believe all the rest should be fine, but will obviously have to test things.
Closes: https://github.com/liferay/liferay-npm-tools/issues/303
> feat(scripts)!: make Babel use preset-react by default (#303)

- packages/liferay-npm-scripts/src/scripts/check.js
- packages/liferay-npm-scripts/src/scripts/check/preflight.js
- packages/liferay-npm-scripts/src/utils/filterGlobs.js
- packages/liferay-npm-scripts/src/utils/getPaths.js
- packages/liferay-npm-scripts/test/utils/filterGlobs.js
We want developers to only use `.babelrc.js`, `.eslintrc.js` (and technically, `.prettierrc.js` too, although there should be exactly one of those in liferay-portal) so that we can format and lint those files, to make sure we get the full benefit of rules like this one:
https://github.com/liferay/eslint-config-liferay/blob/master/plugins/eslint-plugin-liferay-portal/docs/rules/no-explicit-extend.md
To that effect, this commit adds an additional "preflight" step to our "check" script, which means that we now have 3 phases:
1. Preflight checks (currently, these just check for disallowed config file names, but this would be a logical spot to put additional checks in the future).
2. Formatting checks (ie. Prettier).
3. Lint checks (ie. ESLint).
I initially considered baking the check for …
> feat(scripts)!: enforce use of canonical config file names

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
(Weak) breaking change because it means we'll complain about redundant presets that we didn't complain about in the past.
https://github.com/liferay/eslint-config-liferay/releases/tag/v16.0.0
> chore(scripts)!: update eslint-config-liferay to v16.0.0

- packages/liferay-npm-scripts/src/config/eslint.config.js
Otherwise we will get two false positives in liferay-portal when we port the remaining .babelrc files to .babelrc.js:
modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-builder/.babelrc.js
15:1  error  'module' is not defined.  no-undef
modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/.babelrc.js
15:1  error  'module' is not defined.  no-undef
✖ 2 problems (2 errors, 0 warnings)
> fix(scripts): teach ESLint that .baberc.js is a Node module

- packages/liferay-npm-scripts/src/jest/transformBabel.js
- packages/liferay-npm-scripts/src/scripts/test.js
Noticed this in final testing of:
https://github.com/brianchandotcom/liferay-portal/pull/83438
Test runs were failing in two modules (the only ones with .babelrc.js files) with this message:
Multiple configuration files found. Please remove one:
- .babelrc
- .babelrc.js
The problem is this code in the Jest wrapper that was writing a duplicate .babelrc file into the correspond directories. In this commit we teach it to use ".babelrc.js" instead.
> fix(scripts): teach jest wrapper to find .babelrc.js files

- packages/liferay-npm-scripts/README.md
- packages/liferay-npm-scripts/src/utils/deepMerge.js
- packages/liferay-npm-scripts/test/utils/deepMerge.js
These are places where we still talk about ".babelrc" even though we have switched to using ".babelrc.js" files now; none of them should have any meaningful impact on runtime behavior:
- Text in an error message.
- Text in an `it` test description.
- A code comment.
If you `git grep babelrc` you will still find some additional references, but these can stay as they are:
- `runBabel()` still creates temporary .babelrc files, but these always go in a temporary directory (via `withTempFile()`).
- Our storybook wrapper creates .babelrc files too, but always in a temporary directory.
- The bundler preset still has ".babelrc" keys in it, which don't refer to filenames but rather to Babel config in the abstract sense; see: https://github.com/liferay/liferay-js-toolkit/wiki/.npmbundlerrc-file-refe …
> chore(scripts): clean up straggling (but inconsequential) .babelrc references

- packages/liferay-npm-scripts/src/scripts/fix.js
I initially only had the preflight running during the "check" script because it doesn't have any autofix capability and so is never going to fix anything.
But talking with Chema just now it became clear that there is another workflow which is to just blindly run "yarn format" and never "yarn checkFormat". As such, it is possible to send a PR with a problem that would have been caught by the preflight check, only to find out too late in CI (which does "checkFormat") that there is an issue.
Test plan: Copy this change over to liferay-portal, create a bogus config file, and run `yarn format`; see error.
> feat(scripts): run preflight checks during "fix" runs too

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
Provides us with a new "no-loader-import-specifier" rule which will enforce the following:
```js
// Incorrect code:
import useless from './styles.scss';
// Correct code:
import './styles.scss';
```
See: https://github.com/liferay/eslint-config-liferay/releases/tag/v17.0.0
> chore(scripts): update eslint-config-liferay to v17.0.0

- .prettierignore
Because Prettier ignores node_modules by default:
> Prettier CLI will ignore files located in `node_modules` directory. To opt-out from this behavior use `--with-node-modules` flag.
https://prettier.io/docs/en/cli.html
> chore: remove unnecessary line from .prettierignore

- packages/liferay-npm-scripts/src/scripts/check/preflight.js
In https://github.com/wincent/liferay-portal/commit/f7704c187c75117402a8d479ea8c76dcc368b824 we renamed all `.babelrc` files to `.babelrc.js`, and it seems that it [requires some additional changes](https://github.com/lawrence-lee/liferay-portal/pull/146)) (at least those, maybe more) to make the project-templates tasks keep working.
Now, the files under `modules/sdk` are [actually ignored by our `.eslintignore`](https://github.com/liferay/liferay-portal/blob/650fcb63d396ef746999d8c1097b181aec31cc51/modules/.eslintignore#L42) but our preflight checks don't actually use ESLint, and at the time I saw no harm in letting them run over the entire repo — but as you can see above, that assessment was off and the change was not harmless after all.
So, I think it would be reasonable to use the …
> feat(scripts): make preflight checks respect .eslintignore (#354)

- packages/liferay-npm-scripts/src/utils/getJestModuleNameMapper.js
Latent bug in here that I don't think has bitten us in practice, but while testing changes for [LPS-98114](https://issues.liferay.com/browse/LPS-98114), I noticed that I could change imports in the following ways without triggering expected errors:
import {foo} from 'some-module';
// Add a prefix:
import {bar} from 'sssssssome-module';
// Add a suffix:
import {baz} from 'some-moduleeeee';
We need to use stricter matching. The Jest documentation itself points out this pitfall:
> Note: If you provide module name without boundaries `^$` it may cause hard to spot errors. E.g. `relay` will replace all modules which contain `relay` as a substring in its name: `relay`, `react-relay` and `graphql-relay` will all be pointed to your stub.
See: …
> fix(scripts): tighten up Jest module name mapper generation

- packages/liferay-npm-scripts/src/utils/getJestModuleNameMapper.js
I'll be making the requisite changes in liferay-portal to make this workaround no longer necessary (see [LPS-98114](https://issues.liferay.com/browse/LPS-98114)).
Once that is done, all package.json files in liferay-portal will have a "main" that points at an actual file (not a directory), or they won't have a "main" at all.
Closes: https://github.com/liferay/liferay-npm-tools/issues/162
> refactor(scripts): remove DDM special-casing from Jest module mapper

- packages/liferay-npm-scripts/src/config/jest.config.js
- packages/liferay-npm-scripts/src/jest/resolver.js
We have a mix of these two import styles in liferay-portal:
import templates from './Thing.soy';
import templates from './Other.soy.js';
- ".soy": about 93 hits (via `git grep "import.+\.soy'" -- '*.js'`)
- ".soy.js": about 65 hits (via `git grep "import.+\.soy\.js'" -- '*.js'`)
As such, the resolver hack that we had in place for ".soy.js" files was brittle.
In this commit, I make it work for both. If the requested file ends in either extension and passes our `basedir` (ie. own project) check, then we rewrite it, and normalize the extension to always be ".soy.js".
On the source side, I am preparing a commit to liferay-portal that makes us use ".soy" everywhere; in general we don't want an explicit ".js" extension in any `import` statement, because it is inconsistent.
I'll follow that up …
> fix(scripts): make soy resolver overrides work with ".soy" as well

- package.json
- packages/liferay-npm-scripts/package.json
- packages/liferay-npm-scripts/src/utils/getMergedConfig.js
- yarn.lock
Release notes:
https://github.com/liferay/eslint-config-liferay/releases/tag/v18.0.0
Most notably, adds a new ["liferay/import-extensions" rule](https://github.com/liferay/eslint-config-liferay/blob/9274501be1f606de8cb62b8e28e1baa24c17d7af/plugins/eslint-plugin-liferay/docs/rules/import-extensions.md) that disallows (and autofixes) unnecessary ".js" extensions in imports.
Includes autofix for this error:
packages/liferay-npm-scripts/src/utils/getMergedConfig.js
155:26  error  unnecessary extension in import  liferay/import-extensions
> chore(scripts)!: update eslint-config-liferay v18.0.0

- packages/liferay-npm-scripts/src/config/eslint.config.js
Originally included in [the beta release](https://github.com/liferay/liferay-npm-tools/pull/361) I did yesterday, but forget to sent it to master as well, so here it goes.
---
So that we don't have to write custom ESLint exclusions just so that we
can use symbols like `require` in the config files. Will silence output
like:
modules/apps/analytics/analytics-client-js/webpack.config.js
15:17  error  'require' is not defined.  no-undef
16:24  error  '__dirname' is not defined.  no-undef
19:1  error  'module' is not defined.  no-undef
> fix(scripts): treat webpack.config.js as a config file

- packages/liferay-npm-scripts/src/config/eslint.config.js
As described [here](https://github.com/liferay/liferay-npm-tools/pull/363#issuecomment-580724595).
If we grow the list in this way, it enables us to delete 8 of 32 `.eslintrc.js` config files in liferay-portal, and trim down 1 others.
The only thing I am not a huge fan of is having to list `webpack.config.dev.js` separately from `webpack.config.js`; but I think that might be preferable to using a more complicated glob like `**/webpack.config*.js` -- these are the only webpack config files we have the repo in any case and I don't think we'll ever have much more than these:
- `modules/apps/frontend-js/frontend-js-web/webpack.config.js`
- `modules/apps/frontend-js/frontend-js-web/webpack.config.dev.js`
- `modules/apps/analytics/analytics-client-js/webpack.config.js`
> feat(scripts): expand config detection to handle more types

- packages/liferay-npm-scripts/README.md
- packages/liferay-npm-scripts/contrib/prettier/prettier.js
- packages/liferay-npm-scripts/contrib/prettier/prettier.sh
- packages/liferay-npm-scripts/src/index.js
- packages/liferay-npm-scripts/src/scripts/prettier.js
As explained in the README, the intent here is to facilitate editor integration with our customized spin on Prettier. The idea is that instead of using the `prettier` executable, you can use `liferay-npm-scripts prettier` as a more-or-less drop-in replacement.
Next steps will involve showing how to actually use this in some editors, like Vim and VSCode.
> feat(scripts): expose "prettier" subcommand

- packages/liferay-npm-scripts/src/config/eslint.config.js
As explained in the related issue:
In the old days it wasn't actually safe to assume `process` was defined, because not all code passed through the bundler, which is the one that [sets up Babel](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-use-liferay-npm-bundler#an-example) to use the [babel-plugin-transform-node-env-inline package](https://www.npmjs.com/package/babel-plugin-transform-node-env-inline).
But right now, pretty much everything *does* go through it, and we can afford to add `process: true` to our `globals` set-up in one place instead of sprinkling it around in various `.eslintrc.js` files.
The only exceptions I am aware of right now are our frontend-js-web Webpack bundle, which operates in `mode: 'production'` during the build and inspecting the build output I …
> feat(scripts): add "process" to the default list of globals

- packages/liferay-npm-scripts/src/presets/standard/index.js
- packages/liferay-npm-scripts/src/scripts/check/preflight.js
- packages/liferay-npm-scripts/src/scripts/format.js
Please see the individual commit messages for details, but the gist of it is:
- We check against bad dependencies getting added to "package.json" files.
- We format the JSON with Prettier.
Beware: we can't merge this until the bundler issue [described over here](https://github.com/izaera/liferay-portal/pull/125) is fixed, because only then will we be able to remove the bad dependencies from the dynamic-data-mapping-form-field-type project.
> feat(scripts): catch banned dependencies in package.json file

- packages/liferay-npm-bundler-preset-liferay-dev/package.json
- yarn.lock
Just a routine update, like https://github.com/liferay/liferay-npm-tools/pull/374 — as noted there, the duplication in the lockfile is expected and temporary.
> chore(preset): update bundler dependencies to v2.18.1

- packages/liferay-npm-scripts/src/jest/mocks/Liferay.js
- packages/liferay-npm-scripts/src/jest/setup.js
We've provided some mocks for a while now since #77 was created. At this point I think we might as well grab some more low-hanging fruit and then close this one. We can create new issues for specific additions that we'd like to make in the future.
In this commit I add the bits necessary to do the following cleanup in liferay-portal:
https://gist.github.com/wincent/e70a525c667d41c75f81a4084a7f2b31
Closes: https://github.com/liferay/liferay-npm-tools/issues/77
> feat(scripts): expand default mocks provided in test environment

- package.json
Analogous change to this one on the alloy-editor repo:
https://github.com/liferay/alloy-editor/pull/1374
Just in case anybody is ever foolhardy enough to try doing development on this repo on Windows.
> fix(meta): make globs work on Windows

- packages/liferay-jest-junit-reporter/package.json
We shouldn't have explicit devDependencies in our monorepos; they should all be shared and declared at the top level.
Jest already is, so everything continues to work exactly as before (and note: no changes to the lock file).
> refactor(reporter): remove explicit devDependencies

- packages/liferay-jest-junit-reporter/package.json
- packages/liferay-jest-junit-reporter/src/index.js
- packages/liferay-jest-junit-reporter/test/__snapshots__/index.js.snap
- packages/liferay-jest-junit-reporter/test/index.js
Given [John's comment on IFI-780](https://issues.liferay.com/browse/IFI-780):
> This solution does not resolve the root issue.
So, let's revert b50a923 and the follow-ups (418f691 and d52cc87). If we want to take another stab at this in the future we should start again. At the moment, our last non-beta release was 1.0.1 and we'd like to make another (see https://github.com/liferay/liferay-npm-tools/pull/386), but the latest on "master" is 1.1.0-beta.1 and we can't release on top of that. So, we roll back the version change as well (a268cb4) to clear the way for a subsequent release. We'll bump the version number all the way to v1.2.0 to avoid the confusion that may arise from having a "latest" version that is a lower number than a prior release from many months ago.
> revert: undo reporter changes related to IFI-780

- packages/liferay-npm-scripts/README.md
- packages/liferay-npm-scripts/src/config/stylelint.json
- packages/liferay-npm-scripts/src/scripts/lint/stylelint/plugins/sort-imports.js
- packages/liferay-npm-scripts/test/scripts/lint/stylelint/plugins/sort-imports.js
We sort alphabetically, with blank lines used to divide imports into groups. We only sort within groups, never across groups, which means that you can force things to be imported in a certain order if necessary.
Example output on liferay-portal:
https://gist.github.com/wincent/d5e48a398930b327c9cc29291ee35dc3
Example autofix:
https://gist.github.com/wincent/c9dd73cda61e2c3519a280301ba2458a
Note that in there I inserted a blank-line after an `@import "variables"` in page_editor just to show how this can be used to prevent an autosort from being applied; if you look in another file in page_editor in that diff, you'll see what happens if you don't do that.
Closes: https://github.com/liferay/liferay-npm-tools/issues/389
> feat(script)!: sort imports in SCSS files

- packages/liferay-npm-scripts/README.md
- packages/liferay-npm-scripts/src/config/stylelint.json
- packages/liferay-npm-scripts/src/scripts/lint/stylelint/plugins/no-import-extension.js
- packages/liferay-npm-scripts/test/scripts/lint/stylelint/plugins/no-import-extension.js
This is just a simple implementation of the rule that doesn't try to handle compound import statements eg.
@import 'a', 'b', 'c';
because we don't have any of those in liferay-portal. We can add a separate rule to enforce that that invariant remains true, if we want to.
Test plan: Copy this over to liferay-portal and see it make [these changes](https://gist.github.com/wincent/189c5772ae8487b2220a1b638a7bb137).
Closes: https://github.com/liferay/liferay-npm-tools/issues/391
> feat(scripts): disallow explicit .scss extension in imports

- packages/liferay-npm-scripts/package.json
- yarn.lock
In liferay-portal right now, [we've resolved our babel-eslint dependency to v10.0.2](https://github.com/liferay/liferay-portal/blob/52b997396c42fa102a7d850d5f3521d63377423c/modules/yarn.lock#L3637), but that [has a bug in it](https://github.com/eslint/eslint/issues/12117
) causing false positives of the no-unused-vars rule in relation with `for` loops.
By tightening the requirement here, we can force liferay-portal to use the fixed version (we're already on the latest, fixed version of ESLint itself, so no need to worry about that).
Test plan:
Remove [this suppression](https://github.com/liferay/liferay-portal/blob/52b997396c42fa102a7d850d5f3521d63377423c/modules/apps/flags/flags-taglib/src/main/resources/META-INF/resources/flags/soy/Flags.es.js#L113) from the flags-taglib project.
See …
> fix(scripts): avoid false positives involving no-unused-vars

- packages/liferay-npm-scripts/README.md
- packages/liferay-npm-scripts/src/scripts/lint/stylelint/plugins/single-imports.js
- packages/liferay-npm-scripts/test/scripts/lint/stylelint/plugins/single-imports.js
Incorrect:
@import 'a', "b", url(c.css), url('d.css'), url("e.css");
@import 'f', 'g';
@import 'first',
'second',
url('third.css');
Correct:
@import 'a';
@import "b";
@import url(c.css);
@import url('d.css');
@import url("e.css");
@import 'f';
@import 'g';
@import 'first';
@import 'second';
@import url('third.css');
As usual, this is relatively straightforward and only the whitespace-handling is tricky. Take the `@import 'first'...` above, for example: because it is preceded by a blank line, if we just clone it and create three imports for `'first'`, `'second'` and `url('third.css')`, then they will each have a blank line before them, and we don't want that.
So, add some special casing in there to detect blank lines and strip them from the 2nd, 3rd (etc) cloned nodes but keep them on the …
> feat(scripts): enforce one SCSS import per line

- packages/liferay-npm-scripts/src/presets/standard/index.js
As reported [here](https://github.com/brianchandotcom/liferay-portal/pull/85415#issuecomment-592218863), Brian was seeing a bunch of lint errors in frontend-js-aui-web for files
that weren't even touched by the pull. My analysis is:
-   The files with errors were all under "tmp/".
-   You would not expect these files to be checked because we use [globs targeting files under "src/" and "test/", not "tmp/"](https://github.com/liferay/liferay-npm-tools/blob/eee51cbfa7a0ef6a558dc36f6132ea03f0595c5f/packages/liferay-npm-scripts/src/presets/standard/index.js#L10).
-   Any time you "clean" [the "tmp/" directory will get blown away](https://github.com/liferay/liferay-portal/blob/235df4cb7357fbc4116c0240ffef7e03fb0fd0f0/modules/apps/frontend-js/frontend-js-aui-web/build.gradle#L55).
-   By design, …
> fix(scripts): avoid linting files under "tmp/"

- packages/liferay-changelog-generator/src/index.js
Test plan: Regenerate the changelog for liferay-npm-scripts with `../liferay-changelog-generator/bin/liferay-changelog-generator.js --version=liferay-npm-scripts/v28.0.1 --to=liferay-npm-scripts/v28.0.1 --no-update-tags --regenerate`:
https://gist.github.com/wincent/436d53be8351f587f42735d307a48f46
(Note that that requires you to be rebased on top of https://github.com/liferay/liferay-npm-tools/pull/398).
Closes: https://github.com/liferay/liferay-npm-tools/issues/227
> feat(changelog): extract "feat", "fix" information from PR titles

- CONTRIBUTING.md
- packages/liferay-changelog-generator/CHANGELOG.md
- packages/liferay-changelog-generator/README.md
- packages/liferay-changelog-generator/src/index.js
- packages/liferay-jest-junit-reporter/CHANGELOG.md
- packages/liferay-js-publish/CHANGELOG.md
- packages/liferay-npm-bundler-preset-liferay-dev/CHANGELOG.md
- packages/liferay-npm-scripts/CHANGELOG.md
As an example of what these look like, this commit includes changelogs for the packages in this repo (except for liferay-js-insights, which has apparently never been published), made using:
(cd packages/liferay-changelog-generator && bin/liferay-changelog-generator.js --version=liferay-changelog-generator/v1.2.0 --to=liferay-changelog-generator/v1.2.0 --no-update-tags --regenerate)
(cd packages/liferay-jest-junit-reporter && ../liferay-changelog-generator/bin/liferay-changelog-generator.js --version=liferay-jest-junit-reporter/v1.2.0 --to=liferay-jest-junit-reporter/v1.2.0 --no-update-tags --regenerate)
(cd packages/liferay-js-publish && ../liferay-changelog-generator/bin/liferay-changelog-generator.js --version=liferay-js-publish/v1.0.1 --to=liferay-js-publish/v1.0.1 --no-update-tags …
> feat(changelog): add support for per-package monorepo changelogs

- packages/liferay-changelog-generator/src/index.js
Hard to see this in the GitHub UI, but in running the generator over various repos, I found a few odd merge commits that had bad leading whitespace; eg:
https://github.com/liferay/eslint-config-liferay/commit/12a3fbd7426e49d0e86456fb8cbf9bb319bb4b91
(Note the space before the "feat:")
Trim such whitespace off in the output, to avoid creating a disagreement with Prettier (which will insist that the whitespace be stripped).
Test plan: Regen the eslint-config-liferay changelog and see that it no longer contains the unwanted whitespace:
../liferay-npm-tools/packages/liferay-changelog-generator/bin/liferay-changelog-generator.js \
--from=v1.0.1 \
--to=v19.0.2 \
--version=v19.0.2 \
--regenerate
> fix(changelog): don't propagate bad whitespace from PR titles

- packages/liferay-changelog-generator/README.md
> docs(changelog): remove stale "Known limitations" section from README

- packages/liferay-npm-scripts/src/presets/standard/index.js
@julien reported that [this PR](https://github.com/brianchandotcom/liferay-portal/pull/85713) was failing SF checks in CI but not locally.
The cause was that [we had conservative default globs defined at the project level](https://github.com/liferay/liferay-npm-tools/blob/29545e04a57b35b17903aa638c7db2be129995ae/packages/liferay-npm-scripts/src/presets/standard/index.js#L10), so if you run `yarn format` locally from a project, as Julien was, it won't actually look at any JS files outside of "src/" or "test/" — this has been the case [since the beginnings of the preset](https://github.com/liferay/liferay-npm-tools/blob/dc58feb8260e3d71b1546782672d5acc08fd6197/packages/liferay-npm-scripts-preset-standard/index.js#L19) (in fact, back then, it was even more conservative, because it only …
> fix(scripts): make check/fix globs apply consistently at project level

- CONTRIBUTING.md
I just noticed while preparing the release of liferay-npm-scripts v28.0.2 that I hadn't included the full path to the generator in the instructions; ie.
../liferay-changelog-generator/bin/liferay-changelog-generator.js
Let's just simplify the instructions and tell people to use `npx` because that is much easier. We can assume that if you are working on the changelog generator itself and you want to use an unreleased version of the generator then you probably know when not to use `npx` and provide a full path instead.
> docs: update release instructions

- packages/liferay-npm-bundler-preset-liferay-dev/config.json
In addition to the existing support for ".scss" files.
Closes: https://github.com/liferay/liferay-npm-tools/issues/411
> feat(preset): use css-loader for ".css" files

- packages/liferay-js-publish/README.md
By moving it to the top, as suggested [here](https://github.com/liferay/liferay-js-themes-toolkit/pull/451#discussion_r397218823).
And while we're editing, note that we'll soon be using this in liferay-js-themes-toolkit too.
> docs(publish): make non-installation requirement clearer

- packages/liferay-npm-scripts/src/utils/getJestModuleNameMapper.js
Problem reported [in Slack](https://liferay.slack.com/archives/CNBG06JS3/p1585226190005800), analyzed in [LPS-110957](https://issues.liferay.com/browse/LPS-110957), and workaround supplied in [this pull](https://github.com/marcosapmf/liferay-portal/pull/7).
Quoting some of the context:
> As we noted in the Slack thread, the import path starts with: "/js/components/..."
>
> The autogenerated moduleNameMapper has this config in it:
>
> ```
>     "^dynamic-data-mapping-form-builder/(.*)": "<rootDir>../dynamic-data-mapping-form-builder/src/main/resources/META-INF/resources/js/$1",
>     "^dynamic-data-mapping-form-field-type$": "<rootDir>../dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/index.js",
> ```
>
> So it basically appends "/js/components/..." etc to the …
> fix: Make moduleNameMapper work in presence of different module structures

- packages/liferay-npm-scripts/src/presets/standard/index.js
I was asking about this in Slack because I initially thought these were all getting passed to `liferay-npm-bundler`, but `liferay-npm-bundler` doesn't even have most of these properties (only `output`).
So, did a bit of digging to see how each value is used and am documenting it for posterity. There is a risk that this might drift out of sync with the implementation if it changes, but I think it's better to have (possibly) slightly stale documentation than nothing at all.
> docs(scripts): document how "build" preset values are used

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
- [v20.0.0 release notes](https://github.com/liferay/eslint-config-liferay/releases/tag/v20.0.0).
- [v20.0.1 release notes](https://github.com/liferay/eslint-config-liferay/releases/tag/v20.0.1).
Breaking because it [includes a new lint](https://github.com/liferay/eslint-config-liferay/pull/165) (or, not so much a new lint as a additional places where the "liferay/import-extensions" lint rule now applies).
> chore(scripts)!: update eslint-config-liferay to v20.0.1

- packages/liferay-changelog-generator/src/index.js
The idea of this change is to make it easier to generate changelogs in a monorepo with per-package changelogs. At the moment, you have to provide the `--version` flag in the format that corresponds to the version that you are going to release (eg. `--version=liferay-npm-scripts/v28.0.2`).
But we can make that easier for the user by accepting a shorter format (eg. `v28.0.2` or even `28.0.2`), and then automagically doing the right thing by reading the `version-tag-prefix` from the `.yarnrc`.
Test plan: I tried this in a bunch of scenarios to show that it behaves reasonably.
For starters, in this repo, with:
```
../liferay-changelog-generator/bin/liferay-changelog-generator.js --version=$VERSION
```
Valid: `liferay-npm-scripts/v100.10.10+x-1`
Wrote ./CHANGELOG.md 59835 bytes ✨
Invalid …
> feat(changelog): use version-tag-prefix automatically

- packages/liferay-changelog-generator/src/index.js
Prints what would be generated to stdout.
Just a little itch I wanted to scratch. Makes it easier to test changes to the changelog generator.
Test plan:
See changes on stdout:
```
bin/liferay-changelog-generator.js --version=1.4.0 --dry-run
```
Prove that changes can be redirected to a file (ie. changes go to stdout, other messages go to stderr):
```
bin/liferay-changelog-generator.js --version=1.4.0 --dry-run > /tmp/ex
```
Test with `--regenerate` and see a bunch more output:
```
bin/liferay-changelog-generator.js --version=1.4.0 --dry-run --regenerate
```
Show that without `--dry-run`, changelog gets written:
```
bin/liferay-changelog-generator.js --version=1.4.0
```
Show that `-d` is the same as `--dry-run`:
```
bin/liferay-changelog-generator.js --version=1.4.0 -d
```
> feat(changelog): add --dry-run switch

- packages/liferay-npm-scripts/src/jsp/getPaddedReplacement.js
- packages/liferay-npm-scripts/src/jsp/tagReplacements.js
- packages/liferay-npm-scripts/src/jsp/toFiller.js
- packages/liferay-npm-scripts/src/prettier/index.js
- packages/liferay-npm-scripts/test/prettier/index.js
We were doing this in most places thanks to [this change in eslint-config-liferay](https://github.com/liferay/eslint-config-liferay/issues/169), but there were a few places where we didn't enforce blank lines because ESLint and Prettier disagree about comments at the beginning and end of blocks, classes, arrays, objects etc.
Brian would like us to handle those "few places" too, so after thinking about it for a bit, I realized that it is actually quite easy because:
1. We already have this post-Prettier hook in place in liferay-npm-scripts that allows us to override Prettier if needed.
2. We don't need to make a custom lint rule for it; we can just use the existing "lines-around-comment" rule that ESLint provides, appropriately configured.
3. This doesn't fundamentally undermine the main …
> feat(scripts)!: make "blank line before comments" follow Java convention

- package.json
- packages/liferay-npm-scripts/package.json
- yarn.lock
Not a breaking change because the added rule is not on by default.
Release notes:
https://github.com/liferay/eslint-config-liferay/releases/tag/v21.1.0
> chore: update to eslint-config-liferay v21.1.0

- packages/liferay-npm-bundler-preset-liferay-dev/config.json
As explained in the related issue, this config makes it look like "frontend-js-metal-web" provides core-js, but it doesn't, and it seems like it never did (at least not explicitly).
So, we can remove the misleading "core-js" form the preset's "imports".
Note that I also remove the "core-js" entries from the "excludes" section. I don't think this is going to impact the build speed at all because nothing is *actually* depending on core-js at the moment. I spot checked this in a few modules by timing builds with and without the exclude, and looking for any evidence of core-js in the "build/" folder. Couldn't see any difference in:
- frontend-js-web (10 seconds)
- frontend-js-metal-web (16 seconds)
- layout-content-page-editor-web (16 seconds)
All of those I tested them by doing "gradlew …
> fix(preset): remove misleading core-js config

- packages/liferay-npm-scripts/CHANGELOG.md
Caused because I thought the next version was going to be v33.3.0 but then when I actually updated/published (with `yarn version --minor`) I saw that it's actually v32.3.0.
> docs(scripts): fix version numbers in CHANGELOG.md

- packages/liferay-npm-bundler-preset-liferay-dev/config.json
These are the last packages missing from the preset:
- https://www.npmjs.com/package/@clayui/upper-toolbar
- https://www.npmjs.com/package/@clayui/empty-state
We did this yesterday for `@clayui/layout` in 9227c42600a981a30bac8aae6d0a432592d5c929, but I didn't realize that we'd also forgotten these packages (I checked as a result of [this Slack thread](https://liferay.slack.com/archives/C25TXMD63/p1591263042012900)).
I compared with [the current contents of the `frontend-taglib-clay` package.json file in liferay-portal](https://github.com/liferay/liferay-portal/blob/1009dd3a8aa/modules/apps/frontend-taglib/frontend-taglib-clay/package.json) and determined that there is nothing else missing.
> chore(preset): add @clayui/empty-state, @clayui/upper-toolbar to preset

- packages/liferay-changelog-generator/src/index.js
Noticed while looking at [the liferay-ckeditor releases](https://github.com/liferay/liferay-ckeditor/releases) that the links to the "full changelog" are missing the "v" prefix in a lot of places.
That's because the code we have to read the prefix from the ".yarnrc" was inadequately tested outside of monorepos. This small fix makes sure that it reads the top-level ".yarnrc" as well, for the non-monorepo case.
Test plan: Make a merge commit in liferay-ckeditor and run the generator with and without a "v" prefix. Then apply this change and repeat the test; results:
1. "master", with "v" prefix: get valid links in changelog.
2. "master", without "v" prefix: get bad links in changelog.
3. This commit, with "v" prefix: get valid links in changelog.
4. This commit, without "v" prefix: get valid …
> fix(changelog): consistently autodetect prefixes for non-monorepos too

- packages/liferay-changelog-generator/README.md
Because in that project, we switched from top-level changelog to per-package ones.
> docs(changelog): fix broken link in README

- packages/liferay-npm-scripts/src/utils/mergeBabelLoaderOptions.js
- packages/liferay-npm-scripts/test/utils/mergeBabelLoaderOptions.js
And because these loaders now seem to validate their configuration schema, it will throw errors and fail to build:
```
ERROR in ./src/main/resources/META-INF/resources/styles/main.scss
Module build failed (from /Users/brunobasto/Projects/liferay-portal/modules/node_modules/style-loader/dist/cjs.js):
ValidationError: Invalid options object. Style Loader has been initialized using an options object that does not match the API schema.
- options has an unknown property 'overrides'. These properties are valid:
object { injectType?, attributes?, insert?, base?, esModule? }
at validate (/Users/brunobasto/Projects/liferay-portal/modules/node_modules/style-loader/node_modules/schema-utils/dist/validate.js:85:11)
at Object.loader (/Users/brunobasto/Projects/liferay-portal/modules/node_modules/style- …
```
> fix(scripts): don't merge Babel options into webpack loaders other than babel-loader

- packages/liferay-npm-scripts/package.json
[Release notes for the preset](https://github.com/liferay/liferay-npm-tools/releases/tag/liferay-npm-bundler-preset-liferay-dev%2Fv4.6.1).
Motivation: [getting this PR](https://github.com/liferay/liferay-js-toolkit/pull/636) (a bugfix to the "babel-plugin-namespace-amd-define" package).
Updated with:
cd packages/liferay-npm-scripts
yarn add liferay-npm-bundler-preset-liferay-dev@4.6.1
> chore(scripts): update liferay-npm-bundler-preset-liferay-dev to v4.6.1

- CONTRIBUTING.md
There is no need to spell out the full package name, and it is probably a good idea to avoid spelling it out, so as to avoid the possibility of human error.
The generator will automatically prepend the necessary prefix, although it will print a message like:
warning: Replacing unexpected "" prefix with expected
"liferay-npm-scripts/v" prefix in version "32.6.1"
That's what you'd see if you passed `--version=32.6.1`. And if you passed `v32.6.1`, you'd see this:
warning: Replacing unexpected "v" prefix with expected
"liferay-npm-scripts/v" prefix in version "v32.6.1"
So, the warning might scare people, but probably only the first time they see it, so I think this is likely a good change to make.
> docs(CONTRIBUTING): simplify liferay-changelog-generator invocation

- .github/dependabot.yml
Dependabot spams us with update PRs that we don't want to merge because of the reasons described [here](https://github.com/liferay/liferay-frontend-guidelines/blob/master/general/security.md).
Most importantly, there are drawbacks to lockfile-only updates (they are too easily reverted or misunderstood, for example) and we prefer to batch our security updates together based on some human assessment of impact/urgency etc.
So, this setting file should ensure that Dependabot only keeps at most one PR open at a time (the default is 10, I believe), and it runs weekly (the default, I believe). Additionally, given that we want these PRs only as a cue for a human to schedule a periodic manual audit, we turn off automatic rebasing to further reduce noise.
Test plan: Sadly, I don't think I can test …
> chore: configure Dependabot to reduce noise

- packages/liferay-npm-scripts/package.json
[Preset release notes](https://github.com/liferay/liferay-npm-tools/releases/tag/liferay-npm-bundler-preset-liferay-dev%2Fv4.6.2).
Motivating change: [getting this PR](https://github.com/liferay/liferay-js-toolkit/pull/645), which reverts a broken feature.
Updated with:
cd packages/liferay-npm-scripts
yarn add liferay-npm-bundler-preset-liferay-dev@4.6.2
> chore(scripts): update liferay-npm-bundler-preset-liferay-dev to v4.6.2

- packages/liferay-npm-scripts/src/presets/standard/index.js
As per [this comment](https://github.com/liferay-frontend/liferay-portal/pull/384/files#r490801624), in that PR, somebody is avoiding the lint warning about adding `devDependencies`, which we don't allow in liferay-portal for reasons [described here](https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/dev_dependencies.md), by including them in `dependencies` instead. We can catch that by adding a couple more entries to the blacklist. Obviously this is whack-a-mole, but it's way better than having dev dependencies shoved into built JARs.
Test plan: `yarn add` in liferay-portal and see if our `check` script catches the issue on the PR linked above.
> feat(scripts): catch more dev dependencies hiding in non-dev section
